### ISSUE TITLE
Fix "damaged and can't be opened" error

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#151]
This error currently shows up when downloading the replay.dmg and opening it for the first time.  I believe that older DMGs are affected as well.  I think this is probably Apple's fault and things might get better later, but if not this needs to get fixed.  A workaround is to open the terminal enter enter `xattr -cr /Applications/Replay.app` to remove the downloaded-from-the-internet metadata in the folder.

**Comment by jasonLaster** [comment]
The bug boils down to:
1) the user downloads the replay app
2) adds it to the application directory
3) goes to open it

The computer says it is "damaged and can't be opened". 


<img width="532" alt="Screen Shot 2020-08-19 at 1 43 52 PM" src="https://user-images.githubusercontent.com/254562/90688243-05f69400-e223-11ea-8e41-ac3a29a7ae6c.png">

**Comment by bhackett1024** [comment]
This is fixed now.  The problem turned out to be inconsistent capitalization of an executable name --- replay vs. Replay --- in the manifest used during notarization vs. the actual files.  While this is a bug on our side, it's pretty unfortunate that Apple notarized the app but then macs refused to run it after downloading.
