### ISSUE TITLE
Remove unsent crash reports label

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#158]
<img width="349" alt="Screen Shot 2020-09-15 at 1 15 51 PM" src="https://user-images.githubusercontent.com/254562/93260048-a8883100-f755-11ea-8228-ecbbfc66ba32.png">

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-183](https://linear.app/replay/issue/RUN-183/remove-unsent-crash-reports-label)
