### ISSUE TITLE
Allow zooming the timeline

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#16]
I think this might be possible with the current UI but I don't know how to do it, and whether it is currently possible or not it would be nice if there were elements of the UI which could be used to zoom in to parts of  the timeline, or zoom back out.  This would make it a lot easier to deal with the timeline when the recording is long or when there are a lot of messages on it.

**Comment by jasonLaster** [comment]
alt-click and alt-shift-click zoom the timeline. It would be nice if it were possible to zoom via the scroll action though so it is smoother and more intuitive

**Comment by bhackett1024** [comment]
This patch makes the following UX changes:

* The timeline can be clicked and dragged to zoom in on the selected region.  This feels pretty good with the new logic added by #13 to show the screen wherever we are hovering.

* Add a zoom out button next to the timeline.  While there isn't an explicit UI element that users can use to zoom in on the timeline, the presence of this zoom out button indicates that it is possible to zoom, and hovering over it shows a tooltip describing how to zoom in.

* I removed the ability to double click and zoom out on the timeline.  Clicks on the timeline register as jumps now, and we can't really distinguish between single and double clicks without introducing a delay after the first click event to see if a double click is impending.  A click could be used in combination with a keystroke to zoom out (like we do with alt-click to zoom in) or we could just rely on the zoom out button for this functionality.

**Comment by bhackett1024** [comment]
Oh, and when zoomed in we show a percentage on the left and right for the positions of the endpoints in the recording, to help with understanding the current zoom state.
