### ISSUE TITLE
Strange behavior when recording multiple domains in the same tab

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#165]
When starting recording and then navigating to a new domain, the contents of the recording associated with the old recording show up as black when replaying, and scripts from the old domain aren't visible.  The below example started on npr.org and then navigated to replay.io

https://replay.io/view?id=864caac0-be75-4a73-83d3-0ba9ab86c854

**Comment by jasonLaster** [comment]
Here's a replay with two domains (todomvc, github)

the weirdest thing here is that at one point the viewer made it look like we were looking at todomvc, when it probably should have been github

https://www.loom.com/share/fec45fa50a324876b7938eedd63018b7
https://replay.io/view?id=f15cb758-9740-4d83-b312-1d6f018042dc
