### ISSUE TITLE
Improve error handling when recording process can't connect to dispatcher

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#179]
If the recording process is unable to connect to the dispatcher, it will not get a recording ID and will eventually block while it is waiting for that recording ID.  This can happen when finishing the recording or when a resource with a source map is found.  In this case the recording tab will end up going unresponsive, and can't even be closed.  We should do something better here, like loading an error page after a timeout.

**Comment by bhackett1024** [comment]
I don't think this is super important to deal with now, since the UI process connects to the same dispatcher and will not allow creating new recordings when that connection attempt fails.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-24](https://linear.app/replay/issue/RUN-24/improve-error-handling-when-recording-process-cant-connect-to)
