### ISSUE TITLE
Sometimes I need to `./mach build` twice when pointed at custom backend

### ISSUE THREAD

**Issue by jazzdan** [replayio/gecko-dev#210]
Sometimes when I'm changing `gecko-dev` and I run `./mach build` then running `RECORD_REPLAY_DRIVER=~/devel/backend/out/macOS-recordreplay.so RECORD_REPLAY_SERVER=ws://localhost:8000 ./mach run` causes this dialog to appear:

![Screen Shot 2020-11-17 at 5 16 21 PM](https://user-images.githubusercontent.com/452453/99457230-a2026b00-28f8-11eb-8d7e-183ab55bb5ae.png)

If I click "Create New Profile" then the replay browser spins up, but I can't log in. I'm brought to the replay.io/view sign in screen and after signing in the button in the upper left still reads "SIGN IN".

I _think_ this has something to do with how that dialog works. It creates a new process which I think doesn't have the right environment variables associated with it or something.

If I do a `./mach run` with no environment variable overrides after a `./mach build` I can get the Create New Profile dialog to appear, but when clicking it logging in works just fine. If I override `RECORD_REPLAY_SERVER` it doesn't work.

If, after all of this, I run `./mach build` again and then `RECORD_REPLAY_DRIVER=~/devel/backend/out/macOS-recordreplay.so RECORD_REPLAY_SERVER=ws://localhost:8000 ./mach run` I don't get the "Create New Profile" dialog and I am able to log in just fine.

**Comment by ryanjduffy** [comment]
Guessing this isn't a pressing issue since it's been around for nearly a year. Closing under that assumption
