### ISSUE TITLE
You don't have permission to view test failures in CI

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#218]
It looks like when we did the authentication work last week we did not take into account tests.

STR:

1. go to a test failure in CI (https://github.com/RecordReplay/devtools/pull/1063/checks?check_run_id=1451092525)
2. click the link:  Error: Failure inspector-05.js https://replay.io/view?id=604eb265-769c-448d-bd11-89f99e524f09
3. you see an error message in the viewer

<img width="897" alt="Screen Shot 2020-11-25 at 10 49 01 AM" src="https://user-images.githubusercontent.com/254562/100269779-ed75d400-2f0b-11eb-823a-8ff9c33cdb7b.png">

It looks like the problem is that tests for some reason do not receive `msg.data` with the `RecordingFinished` event and bail early. I just tested this locally and saw the same thing. The fix should be fairly straight forward because we should be able to fix the event in `module.js` and then everything should work. It's pretty great that Dan's comment describes this perfectly.

```js
Services.ppmm.addMessageListener("RecordingFinished", {
  async receiveMessage(msg) {
    // NOTE(dmiller): this can be null in the devtools tests for some reason, but not in production
    // Not sure why.
    if (isRunningTest() && !msg.data) {
      console.log("got RecordingFinished with empty msg data, skipping");
      return;
    }
```

**Comment by loganfsmyth** [comment]
I'm actually a little confused about what was going wrong with this to begin with, but it looks like it is working now? I'd have expected _two_ `RecordingFinished` events, one with data, and one without, so the second one still would have set the permissions. Maybe there's something I'm missing though.
