### ISSUE TITLE
Design New Tab

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#241]
The new tab page is currently blank. This is a missed opportunity to help people 

1. start the recording process 
2. find their library
3. log in, log out, or switch accounts
4. ...

<img width="1127" alt="Screen Shot 2021-05-16 at 10 43 04 AM" src="https://user-images.githubusercontent.com/254562/118407023-84a62380-b633-11eb-9a47-dc07b8cb2513.png">

**Comment by jasonLaster** [comment]
I started a new figma exploration here. 

https://www.figma.com/file/SSr1ljyzF0lCXTL7BX1Whh/Replay-Design-Doc?node-id=3977%3A7915

<img width="8931" alt="new tab" src="https://user-images.githubusercontent.com/254562/118408231-7fe46e00-b639-11eb-8805-30f7058e26c3.png">

**Comment by jasonLaster** [comment]
This is a technical detail, but lets build the new tab page in the DevTools repo. The advantage is that we will 

1. be able to easily edit and avoid deploying a new browser
2. DevTools has auth built in
3. DevTools has our CSS /JS components which will help us be more consistent

**Comment by jonbell-lot23** [comment]
Proposed MVP: 
![](https://user-images.githubusercontent.com/9154902/119411522-ab084500-bd3e-11eb-82d7-4feff583599f.png)

More details in Notion for follow-on features:
https://www.notion.so/replayio/New-Tab-Design-c60abe597c2e4bd1b5a01cc9847ffc96

**Comment by ryanjduffy** [comment]
I took a pass at adding this to the website tonight. It looks fine but the load time is pretty poor so I think we might need to either embed it or create some sort of hybrid page (arch tbd!).

https://user-images.githubusercontent.com/788456/119444371-f808fe80-bcdf-11eb-8268-8014503c5ac3.mp4

**Comment by jonbell-lot23** [comment]
Awesome! I'm having trouble seeing the video because I think it's cropped.

I can't tell where the delay is. Is the tab opening immediately when you click the + icon, or is that delaying by 1-2 seconds?

**Comment by ryanjduffy** [comment]
It's delayed by a couple seconds. I think I've sorted it out though. Pushing a couple PRs shortly!
