### ISSUE TITLE
Website behaves differently while being recorded

### ISSUE THREAD

**Issue by jaril** [replayio/gecko-dev#246]
Webflow University (https://university.webflow.com/) has a search box right by the hero image. Typing "grid" inside it usually shows a autocomplete list of grid-related content. The same list does not appear when recording the website.

STR:
1. go to https://university.webflow.com/
2. start recording
3. type "grid" in the search box

https://www.loom.com/share/561b5625944146cdbef2c163101657e7

![image](https://user-images.githubusercontent.com/15959269/101846727-7002b400-3b06-11eb-95d5-68736ea30ceb.png)

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-26](https://linear.app/replay/issue/RUN-26/website-behaves-differently-while-being-recorded)
