### ISSUE TITLE
Twitter embedded videos not working in Replay browser

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#248]
When you go to Twitter and look at a timeline, embedded videos don't work.

STR:
1. Visit https://twitter.com/realDonaldTrump in Replay
2. Suppress gag reflex
3. Look for embedded video of Trump trying to subvert democracy
4. Video doesn't play and shows Twitter error: The media could not be played

**Comment by jasonLaster** [comment]
moved the issue to gecko-dev to track Replay browser bugs.

In this case, i would expect the video to work in Replay, but not while recording

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-187](https://linear.app/replay/issue/RUN-187/twitter-embedded-videos-not-working-in-replay-browser)
