### ISSUE TITLE
Updated Replay browser tells me to update

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#250]
1. Tried to do something with Replay and it told me to update
2. I updated successfully, and there are no more updates available
3. But I'm seeing this page anyway:

<img width="1095" alt="image" src="https://user-images.githubusercontent.com/9154902/102004681-cf1b2f80-3d77-11eb-93ac-4bce23648223.png">

I assume this is happening because the browser is showing the last tab I was viewing before restarting.

**Comment by jonbell-lot23** [comment]
Is this a technical issue, where the screen shouldn't show at all? Or is it something that could benefit from better copy/visual design? If it's the latter, let me know and I can put something together.

**Comment by ryanjduffy** [comment]
This seems fixed (and is rather old at this point) so I'm closing.
