### ISSUE TITLE
Cannot record https://mastery.games/gridcritters/

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#251]
Recording https://mastery.games/gridcritters/ signin page goes white

here's the recording i get https://replay.io/view?id=612c1656-20e6-48be-8b53-aa14e1a03286

**Comment by bhackett1024** [comment]
An exception is being thrown because we don't support using AudioContext when recording/replaying.  See the comment here:

https://replay.io/view?id=6b73662a-9b16-4a76-bce2-e32188076152
