### ISSUE TITLE
Upgrade popup copy is missing

### ISSUE THREAD

**Issue by jaril** [replayio/gecko-dev#252]
![image](https://user-images.githubusercontent.com/15959269/102822889-e07fbf80-43a7-11eb-8d19-f71ae9bf3fe6.png)

Moved from https://github.com/RecordReplay/devtools/issues/683

**Comment by loganfsmyth** [comment]
Seems similar to https://github.com/RecordReplay/gecko-dev/issues/226 too. There must be something weird with the styling for these or something.

**Comment by bhackett1024** [comment]
I saw a similar issue to this some months back where some code in intl/l10n/Localization.jsm that tries to asynchronously localize resources was broken for a reason I couldn't determine, causing quite a bit of the browser's UI (like the about page and the session restore page) to render without any text.  I "fixed" this by forcing this localization to happen synchronously, but the underlying problem still remains.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-28](https://linear.app/replay/issue/RUN-28/upgrade-popup-copy-is-missing)
