### ISSUE TITLE
Addon support

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#267]
It should be possible to add addons to the Replay browser such as react devtools. At the moment, you get this error

https://addons.mozilla.org/en-US/firefox/addon/react-devtools/

<img width="944" alt="Screen Shot 2021-01-07 at 11 18 02 AM" src="https://user-images.githubusercontent.com/254562/103934663-3360b300-50da-11eb-871d-5ccf391fee4d.png">

**Comment by jasonLaster** [comment]
Passing along the feedback for addons

Replay is Firefox, so: https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager/ Maybe that would work?

**Comment by jasonLaster** [comment]
This came up when talking to the glide folks. Also noticed it today because I wanted golinks :)

**Comment by ryanjduffy** [comment]
This may have been fixed incidentally along the way. I was able to install 1Password and React Dev Tools tonight on the release build of Replay on Mac.

**Comment by jasonLaster** [comment]
Oh wow! Very cool.
