### ISSUE TITLE
Remove toolbar clutter

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#27]
I've already removed some toolbar buttons that are shown in a normal firefox browser, but the toolbar still has too much clutter.  The following buttons should be removed:

Home button - This doesn't seem so important these days (I never click on it) and distracts from the recording button next to it.

Bookmarks/history button - This is pretty minor and I don't think people using this browser will be super interested in it.

Sidebar button - Ditto.

**Comment by jasonLaster** [comment]
The browser toolbar is the primary UI surface area that users will interact with

- left navigation should feel comfortable
- right actions should be as usable as possible
  - it should be easy to start a recording
  - it should be easy to upload a recording


[figma](https://www.figma.com/file/0thWEmltivv3Xov5KlluIV/Replay-UI?node-id=0%3A1)
![simplified toolbar](https://user-images.githubusercontent.com/254562/73697772-42eaa700-4694-11ea-960e-90f136e96e3e.png)

**Comment by bhackett1024** [comment]
I removed the buttons above and increased the size of the recording button to make it more prominent, but there is definitely more to do in followup.  It would be nice to remove the doorhanger and expose all the functionality by clicking on toolbar buttons, as your figma shows.
