### ISSUE TITLE
Sign in page has two buttons - one works and one doesn't

### ISSUE THREAD

**Issue by lisahackett1978** [replayio/gecko-dev#276]
Steps to reproduce
1. Start with a fresh firefox profile

2. Open Replay browser

3. Try clicking the "Sign In" button at the top. It looks like this top button might simply be refreshing the page.
![Screen Shot 2021-01-14 at 1 53 08 PM 1](https://user-images.githubusercontent.com/77456982/104816394-1f066f80-57d8-11eb-9ca2-fdd634b21d6c.png)

**Comment by loganfsmyth** [comment]
I'm going to close #183 in favor of this since this one has more of a description.

Basically the issue is that only the button in the page is actually a login button, the button in the toolbar just opens https://replay.io so that you _can_ log in. It is very confusing.

**Comment by jasonLaster** [comment]
I think we have two options

1) don't show the **sign in** button if we're viewing `replay.io/view`
2) when the user clicks the global **sign in** button, the browser can send a message to the page instructing it to sign in. The page likely could call an auth0 method to start the sign in process or do something like `document.querySelector("signin").click()`

1 is easy, but not satisfying. 2, should be doable, but might run into some traps.

**Comment by loganfsmyth** [comment]
Could we have the toolbar button redirect like it does now, but have a `/login` URL that immediately runs the login flow? Then we don't need to send messages or anything.

**Comment by jasonLaster** [comment]
yeah, i think we just need to see what works :)

**Comment by lisahackett1978** [comment]
These all sound like great options. We could also eliminate that first login screen entirely, and instead take users here when they open the browser. Simplifying the login flow would make users happier. :)
<img width="1244" alt="Screen Shot 2021-01-22 at 8 17 10 AM" src="https://user-images.githubusercontent.com/77456982/105509456-c0833a80-5c8a-11eb-9b00-61ffe013fdcd.png">
