### ISSUE TITLE
Responsive Design Mode makes recordings unresponsive

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#282]
1. open the dev tools
2. use the Responsive Design Mode
3. start recording with Replay

then, the page won't load fully and is not interactive at all :thinking: made a small video with reproduction steps, hope you'll find it useful: https://imgur.com/a/VrYaSxG

**Comment by jasonLaster** [comment]
From Kacper:

> We had some issues regarding "disappearing" modal on mobile devices which was quite hard to replicate and occuring rarely, so it was a perfect use-case for Replay

**Comment by jasonLaster** [comment]
This makes me want to make responsive design mode and network throttling a much more central part of the recorder...

We should probably consider elevating those buttons to the browser toolbar

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-189](https://linear.app/replay/issue/RUN-189/responsive-design-mode-makes-recordings-unresponsive)
