### ISSUE TITLE
Lots of rendering issues on Apple's iPad page

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#283]
A lot of items aren't loading on this page. I captured a Replay here:
https://replay.io/view?id=944a4417-0cc9-41b8-8c92-9bd234ecff07

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-190](https://linear.app/replay/issue/RUN-190/lots-of-rendering-issues-on-apples-ipad-page)
