### ISSUE TITLE
[UX] "Welcome to Firefox" message is confusing

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#288]
We're showing this message on load:
![image](https://user-images.githubusercontent.com/9154902/106658225-e3560d00-6601-11eb-97a9-4eac5b81ea8b.png)

But we should remove mentions of Firefox because it's confusing

**Comment by ryanjduffy** [comment]
@jasonLaster, @loganfsmyth - Do you know under which conditions this screen is rendered? I've found where to update it and I could scrub the content of FF references but I'm not sure that's the right thing to do since the content doesn't really apply.

**Comment by jasonLaster** [comment]
Nope - I think that's probably the next step. 

A lot of this work is first investigation and then coming up with reasonable suggestions 😉

**Comment by ryanjduffy** [comment]
`about:newinstall` is the trigger. At least one vector is launching replay when you previously had FF developer edition installed. The relevant source seems to be `browser/components/BrowserContentHandler.jsm`.

**Comment by ryanjduffy** [comment]
Looks like the decision logic is housed in `toolkit/profile/nsToolkitProfileService.cpp`. I'm not following all of the logic but it does seem like the general spirit of that page is: "You had a profile but we can't use it for some reason so we want to let you know and prompt you to use FF Accounts to sync them".

My first inclination is that we probably don't need this view at all, at least in the near term, and would be better off suppressing it.

**Comment by ryanjduffy** [comment]
STR:
* Delete/Rename Firefox directory containing your profiles
* Launch Firefox Developer Edition and close once it successfully launches
* Launch Replay

Expected:
* Replay launches with replay.io homepage

Actual:
* replay.io is launched along with "Important News" tab and dialog

**Comment by jasonLaster** [comment]
Thanks!
