### ISSUE TITLE
Run Playwright scripts in the cloud

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#298]
Playwright has a docker image that _just_ works, perhaps we can build on top of it...

https://hub.docker.com/_/microsoft-playwright
https://playwright.dev/docs/docker/
https://github.com/microsoft/playwright/blob/master/utils/docker/Dockerfile.bionic

**Comment by bhackett1024** [comment]
We have a docker image now that can be used to record playwright scripts, see https://github.com/RecordReplay/devtools/blob/master/test/playwright/README.md for installation instructions.
