### ISSUE TITLE
Publish Playwright browser builds

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#299]
Providing builds via our website so that people can use replay+playwright builds very easily

**Comment by bhackett1024** [comment]
We have download links now for playwright browser builds:

https://replay.io/downloads/macOS-replay-playwright.tar.xz
https://replay.io/downloads/linux-replay-playwright.tar.xz

These browsers pass >99% of playwright's test suite when recording.  We also have a docker image `recordreplayinc/playwright:latest` with the linux+replay+playwright browser preinstalled.

Another option would be to support downloading the builds by setting PLAYWRIGHT_DOWNLOAD_HOST (see https://playwright.dev/docs/installation), but this is more complicated and we would also have to host the other binaries playwright needs I think and keep them in sync with upstream.  It seems best to hold off on that until we see a clear need for it.
