### ISSUE TITLE
Can't login via Google or Twitter on skittish.com (But it works in Chrome)

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#304]
1. Go to https://little.skittish.com/event/xoxotest
2. Click the login buttons for Twitter or Google
3. The page attempts to auth, but then returns back to the login screen.

Here's a Replay of me attempting to log in. It eventually works when set up a new account via email:
https://replay.io/view?id=4499195b-f61b-4fbd-8983-6ce0b3c11e4a

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-33](https://linear.app/replay/issue/RUN-33/cant-login-via-google-or-twitter-on-skittishcom-but-it-works-in-chrome)
