### ISSUE TITLE
[UX] When recording WebGL, show error message explaining why the region has gone white

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#305]
1. Load skittish page
2. Press record button in Replay browser
3. Page goes white

Here's a video of it:
https://share.descript.com/view/jCb13LOP0ZP

And here's a Replay:
https://replay.io/view?id=35319825-99f4-4ea3-939f-47b64375f7c5

**Comment by bhackett1024** [comment]
It looks like the problem is that the page is using WebGL, which we don't support while recording.

**Comment by jonbell-lot23** [comment]
Ah. Ok, renaming bug to reflect that we should should show an error message where possible.

**Comment by bhackett1024** [comment]
dupe of https://github.com/RecordReplay/gecko-dev/issues/314
