### ISSUE TITLE
Resn.co.nz doesn't load when Replay is recording

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#306]
Here's what happens:
https://share.descript.com/view/VVpG76xai3D

Here's the Replay that goes along with that Descript recording:
https://replay.io/view?id=bee64174-fcaa-475b-aa5c-e24abc6529f5

STR:

1. Go to http://resn.co.nz in Replay browser
2. The page loads correctly with fancy animations
3. Press record button; page reloads and begins to record
4. Loader stalls out instead of loading successfully

**Comment by jasonLaster** [comment]
This feels like an example of an app that is outside of our sweet spot.

**Comment by jonbell-lot23** [comment]
Fair, but part of defining a sweet spot is making sure we message when we can't do something.

So if it's a webGL issue we should message that. And if it's some other issue we should message that instead.

**Comment by jasonLaster** [comment]
Yep. That's part of project focus
https://github.com/RecordReplay/devtools/issues/1905

**Comment by jonbell-lot23** [comment]
Perfect!
