### ISSUE TITLE
flowchart.fun crashes while recording

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#308]
STR:

1. go to https://flowchart.fun/
2. type nodes into the editor, in my example I added links with new lines and indentation
3. save the recording

```
and a new top level node
  which has some things
  links: (4)
  foo: (5)
```

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-34](https://linear.app/replay/issue/RUN-34/flowchartfun-crashes-while-recording)
