### ISSUE TITLE
disable popup blockers for replay.io

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#313]
The popup blocker should be disabled for replay.io so that users can easily sign in

<img width="1792" alt="Screen Shot 2021-03-04 at 6 17 08 PM" src="https://user-images.githubusercontent.com/254562/110057730-f7328300-7d15-11eb-83bd-e02f3960ec3d.png">

**Comment by jasonLaster** [comment]
https://searchfox.org/mozilla-central/source/toolkit/actors/PopupBlockingParent.jsm
https://searchfox.org/mozilla-central/source/docshell/base/BrowsingContext.cpp#2089

properties: https://searchfox.org/mozilla-central/source/browser/locales/en-US/chrome/browser/browser.properties#255-272

toggle: https://searchfox.org/mozilla-central/source/browser/base/content/browser.js#1115

we might be able to do this when we see that we're browsing replay.io

      gBrowser.selectedBrowser.popupBlocker.unblockAllPopups();

**Comment by ryanjduffy** [comment]
I put together a branch that might help with this but I haven't been able to reproduce a popup so I'm not sure.

@jaril or @jasonLaster - If you could attach a replay / video of the STR, that'd be really helpful!

https://github.com/RecordReplay/gecko-dev/compare/webreplay-release...RecordReplay:ryan/allow-popups?expand=1

**Comment by jasonLaster** [comment]
Thanks @ryanjduffy. I couldn't repro either.

My steps were:
1. go to `about:profiles` and creating a new profile
2. sign in
