### ISSUE TITLE
Creating a WebGL context should return null instead of throwing

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#316]
Currently we throw an exception when creating a WebGL canvas context, because replay doesn't support WebGL (https://github.com/RecordReplay/gecko-dev/issues/58).  Looking through the documentation for canvas.getContext(), it's valid behavior to return null when a type of context isn't supported.  We should do that instead of throwing to improve web compat and reduce problems like https://github.com/RecordReplay/gecko-dev/issues/305 and https://github.com/RecordReplay/devtools/issues/2072.

**Comment by jasonLaster** [comment]
👍 I think this would also help @wuweiweiwu and the http://nashi.io/ folks who have a webGL component in their app
