### ISSUE TITLE
[Linux] Can't record a click on an unstyled button

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#328]
The following issue only occurs with the Linux browser: when I click on an unstyled button while recording, the recording can't be viewed (Session died unexpectedly).
My guess is that this has to do with the fact that the button is rendered using a native widget (explaining why the issue is platform-specific).
Here's a successful recording containing an unstyled button, but no click on it:
https://replay.io/view?id=d43d3fdc-936b-499e-b329-6d878ab082ac
A failed recording containing a click on the unstyled button:
https://replay.io/view?id=208b29c1-af98-49f7-abc5-c8580744f1a3
A failed recording containing a click on the button with `style="color: red"` (this is still rendered with a native widget):
https://replay.io/view?id=d0b860b5-49b9-456a-9cb0-f3a20bf924c3
A successful recording containing a click on the button with `style="background-color: red"` (this doesn't use a native widget):
https://replay.io/view?id=e2fb7ab0-9b32-4e8f-9fe4-c41ee0608cce

**Comment by bhackett1024** [comment]
This should work using the latest driver, https://github.com/RecordReplay/backend/issues/1671 has some more info about what was going on here, but yeah, we weren't dealing with a library call (gtk_render_focus) which gecko makes when clicking on unstyled buttons.

**Comment by bhackett1024** [comment]
Oh, I haven't confirmed this works, so if you have a chance sometime to verify that would be great.

**Comment by hbenl** [comment]
I just verified that this works now.
