### ISSUE TITLE
While uploading, the URL in the address bar is wrong

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#330]
Recording showing the issue: https://share.descript.com/view/aGHWj17qApa

When you press stop, the Replay browser begins its upload process, but the URL still shows the old place where you were. I'm filing this issue as its own bug, but it's related to other tasks where we're saying we should be targeting a new tab when the upload starts.

**Comment by jasonLaster** [comment]
We should probably do a sprint around saving a replay in gecko-dev

- url bar
- open in a new tab
- faster loading screen with resources uploaded in the background

**Comment by ryanjduffy** [comment]
@jonbell-lot23 , @jasonLaster  - Can this be closed now that launching in a new tab has landed?

**Comment by jonbell-lot23** [comment]
Yup!
