### ISSUE TITLE
disable firefox accounts

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#331]
When i was sitting with Miriam, i noticed she started going through the firefox accounts setup. We should simplify the onboarding to disable Firefox specific onboarding

<img width="1110" alt="Screen Shot 2021-04-09 at 9 23 49 AM" src="https://user-images.githubusercontent.com/254562/114211360-643cc800-9915-11eb-9a32-d8de4cd84e6f.png">

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-35](https://linear.app/replay/issue/RUN-35/disable-firefox-accounts)
