### ISSUE TITLE
Can't jump to console logs in debugger-evaluated code

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#333]
If a console.log() call is injected by the debugger (for example via playwright), the resulting message can't be jumped to when replaying.  We'll consider the debugger code to be a browser internal source and won't be able to show the frames etc., but should still be able to jump to that point with no frames on the stack.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-37](https://linear.app/replay/issue/RUN-37/cant-jump-to-console-logs-in-debugger-evaluated-code)
