### ISSUE TITLE
Some recordings are truncated when running playwright tests

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/gecko-dev#335]
I've had a couple instances while working on playwright tests where the replay is truncated. Sharing the PRs since they can be used to repro the issue. Replay links are in the PR description.

https://github.com/RecordReplay/playwright-tests/pull/37
https://github.com/RecordReplay/playwright-tests/pull/34

**Comment by bhackett1024** [comment]
I wasn't able to reproduce this, but for the first one I can see that the upload didn't finish before the connection closed --- the driver sends a JSON description of the recording at the end, and that wasn't received by the backend.  Are you still able to reproduce this?  Running with `DEBUG=pw:browser*,pw:api` set should help with diagnosis, to see if there was a connection problem or the recording process was prematurely terminated.

**Comment by ryanjduffy** [comment]
This doesn't seem to repro for me any longer either. Closing
