### ISSUE TITLE
Download image missing folder background image

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#337]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/9154902/114791355-7d90b900-9dda-11eb-87db-fcb4e4fe433b.png">

I believe we used to have a background image here. If so, let's put it back. (As a follow-up, we'll probably need to add some additional messaging in the bg) If I'm misremembering, let's close this issue and deal with it later.

**Comment by jasonLaster** [comment]
@jonbell-lot23 can you design a better download image folder?

**Comment by jonbell-lot23** [comment]
It's back to having a blue background, which works for me.

**Comment by ryanjduffy** [comment]
When just tried this it was a white background (again?).

@loganfsmyth , @bhackett1024 - Do either of you have any background (pun intended) on what might have changed? I didn't see any recent commits in gecko-dev so I'm wondering if there is some bundling code elsewhere that is adding this.

**Comment by bhackett1024** [comment]
I don't know what happened, but when I download the DMG and try to open it I also see the plain white folder.  The code which builds the DMG in a way that it shows a nice install UI is here:

https://github.com/RecordReplay/backend/blob/8d3e4500fd84a955906886e086a31b57c5fac236/src/build/buildGecko.ts#L237

This has had changes over time separate from those in gecko-dev.

**Comment by ryanjduffy** [comment]
:+1: I'll start there. Thanks!

**Comment by ryanjduffy** [comment]
When I run the build script locally, the background is applied. Are the commands logged when they run through the build/deploy process? I wonder if it's using the wrong path for some reason to the background image causing the option to be ignored.

<img width="522" alt="image" src="https://user-images.githubusercontent.com/788456/118324601-1a687400-b4b7-11eb-9c27-93f17952cb8f.png">

**Comment by bhackett1024** [comment]
We do generate logs when deploying new builds.  It would probably be best to debug on the macstadium machine where we do deploys from, there are instructions at https://github.com/RecordReplay/backend/blob/master/docs/services.md#deploying-new-builds and you can get the machine's credentials by asking on discord.

**Comment by ryanjduffy** [comment]
With @jazzdan's help, the current (as of now) version has the background again. The root cause appears to be either:
* You have to run the build + deploy script via VNC so `create-dmg` can mount the image and launch finder which creates the necessary .DS_Store file, or
* You have to do that at least once to update the Mac permissions.

We'll know more if we run the next release via `ssh` instead and the background remains or not!

**Comment by jasonLaster** [comment]
Thanks @ryanjduffy. Out of curiosity, it there an easy way to test this?

**Comment by ryanjduffy** [comment]
Downloading the latest installer should include the fix. Once you mount it, it should have the blue background and arrow

**Comment by jasonLaster** [comment]
Got it. Was thinking about an automated test to verify that the build had what it needs... something in the package dir

**Comment by ryanjduffy** [comment]
Seems that the existence of the `.DS_Store` file is the critical bit so we could probably check for that. I can look into it.
