### ISSUE TITLE
[UX] When pressing record, we should explain the page reload

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#339]
Almost every user we interview expresses surprise that Replay needs to reload, and it sometimes causes them to lose state and work.

Pressing record should trigger a prompt that explains that we're about to reload (and why), then provide [OK] [Cancel] buttons alongside a [Don't show this again] label. Design to come.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-198](https://linear.app/replay/issue/RUN-198/[ux]-when-pressing-record-we-should-explain-the-page-reload)
