### ISSUE TITLE
Scrolling is dropping paints

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#344]
Scrolling with either the scrollbar or wheel seems to drop paints when replaying

### STR
1. go to https://codepen.io/bluefantail/live/mdRYgPa
2. scroll with the mouse wheel
3. scroll with the scrollbar

### Replays
1. https://replay.io/view?id=ac15c913-f837-41bc-a472-f26c74c977b7
2. https://replay.io/view?id=ec73f465-358a-48b2-99be-759e333675a9&point=13305260700041495060300200824275420&time=6723&hasFrames=false

**Comment by bhackett1024** [comment]
This is working better now, we disabled APZ in https://github.com/RecordReplay/gecko-dev/issues/292 and should see the different paints during scroll actions when replaying.
