### ISSUE TITLE
Exceptions while replaying

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#345]
Replaying this [checkly](https://github.com/RecordReplay/playwright-tests/blob/main/examples/checkly.js) playwright script generates a lot of replaying exceptions which are probably issues we have while replaying.

* vendor.42cac369.js:97 Exception RangeError: "invalid or out-of-range index"
* TypeError: "`argumentsList` argument of Reflect.apply must be an object, got (void 0)"
* vendor.42cac369.js:6304 Exception TypeError: "Number.prototype.toFixed called on incompatible Object"
* vendor.42cac369.js:97 Exception RangeError: "invalid date"
* vendor.42cac369.js:97 Exception TypeError: "calling a builtin ArrayBuffer constructor without new is forbidden"
* vendor.42cac369.js:5693 Exception TypeError: "invalid Array.prototype.sort argument"
* vendor.42cac369.js:97 Exception TypeError: "can't convert null to object"
* chunk-vendors.2b07469e.js:23468 Exception TypeError: "Invalid type: first can't be a Regular Expression"

https://replay.io/view?id=447862fb-8716-454c-9df5-d9170561fbea&point=36995115119955335297599016873754794&time=13407.019675125219&hasFrames=true

**Comment by bhackett1024** [comment]
There's no evidence here that replay is behaving incorrectly.  If the page originally threw these exceptions while recording, we're just showing them while replaying.
