### ISSUE TITLE
print statement in `engine.js#draw` is missed

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#347]
STR:
1. go to  https://mopaint.app/?document=BQNavW_0B
2. add a logpoint inside of engine.js:draw on line 13
3. draw on the canvas

Notice how it is called a lot

1. go to https://replay.io/view?id=cec7b450-be59-4439-bfa1-24d582af5d4e
2. add a breakpoint in engine.js:draw on line 13

notice it is only called twice

**Comment by hbenl** [comment]
I don't see any interactions in that recording, the mouse pointer doesn't even move. I made a new recording of mopaint and get a lot of hits in `engine.js`: https://replay.io/view?id=e2e66142-5508-4021-9415-a3feff767dab
