### ISSUE TITLE
Initial page load can take awhile

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#352]
When the user clicks record, the initial page load can take considerably longer than it would otherwise. We should investigate ways to improve the performance.

One option would be to preload the recording process https://github.com/RecordReplay/backend/issues/1088

> Similar to controller preloading, when someone wants to start recording a tab and clicks the "record" button, the recording process starts up from scratch and has to connect to the UI process and initialize before any content can start loading.
>
> Gecko has a way to preload content processes to avoid this delay, see ContentParent::GetUsedBrowserProcess. This code is currently disabled (it caused some rendering problems in the presence of recording processes), but if it was reenabled and updated so that we could preload a recording process, then we would improve responsiveness when starting recording.

**Comment by loganfsmyth** [comment]
From my own tests, a large portion of the slowness is also present when reloading a page in an existing recording, so we should probably focus on that first rather that on spawning the child process early.

**Comment by loganfsmyth** [comment]
The baseline I'm seeing for this, when recording https://replay.io/view, is that a page reload takes about 3-4ish seconds when not recording, vs when refreshing a tab that is already recording takes 10-11ish seconds, counting from pressing refresh to the point where the recording thumbnails start showing up, and that is when running the backend locally. An additional 7 seconds is definitely not ideal.

**Comment by jasonLaster** [comment]
cc @bhackett1024

**Comment by jasonLaster** [comment]
Here's a video which shows another example of the reloading taking awhile
https://www.loom.com/share/50da9e08a95c4596bf743d52ae6943dd

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-39](https://linear.app/replay/issue/RUN-39/initial-page-load-can-take-awhile)
