### ISSUE TITLE
NYTimes upload stalled

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#355]
* Recorded for 20 seconds
* Successful recording Replay sent almost immediately
* Upload stalled out indefinitely

Here's the Replay:
https://replay.io/view?id=c22c54ab-d7c3-4a73-93ea-fa085a17e2d6

**Comment by jonbell-lot23** [comment]
Just had the same thing happen. Here's another example: https://replay.io/view?id=73d2a569-9844-4d88-a2ca-17dc1c7bb466

Each time I load this, the session dies unexpectedly.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-40](https://linear.app/replay/issue/RUN-40/nytimes-upload-stalled)
