### ISSUE TITLE
Add "Welcome Tab"

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/gecko-dev#361]
FF includes `about:newinstall` and `about:welcome` built-in pages. The former is triggered when a new profile is created on an existing install (this was hidden via #357) and the latter is triggered for a first-time install.

## about:welcome

<img width="1392" alt="Screen Shot 2021-05-14 at 9 15 55 AM" src="https://user-images.githubusercontent.com/788456/118301395-d7e36f00-b497-11eb-94d1-6409351ae079.png">

**Comment by ryanjduffy** [comment]
This ties into #331 since this first page prompts for sign in to FF Accounts.

**Comment by ryanjduffy** [comment]
Proposing that we "combine" both conditions (newinstall and welcome) into the welcome page so that users with an existing FF and non-FF users installing Replay both get the same welcome view (`about:welcome`).

Thoughts on this approach? Are there any existing onboarding designs I can pull from for this?

cc: @jasonLaster, @jonbell-lot23, @jaril

**Comment by jonbell-lot23** [comment]
Great questions, and great initiative, @ryanjduffy.

1. Any existing designs to pull from for this? Nope. At this point we're optimising for generic and consistent. This fits in well to our approach so far, and feel free to play with it a bit.

2. As for the copy and flow itself: at this stage, people need to a) sign in b) optionally import their passwords from Chrome c) Be told how to start their first recording. I would like this to be clear and concise with as few screens as possible. I was thinking something like this:

Screen one:
[Welcome!]
[Description text]
[Click here to sign in with Google]

Screen two:
[Success!]
[Import your settings from Chrome] or [Get started with your first recording]

Getting started flow:
[Header]
[See that record button at the top right? Open a new tab and press it!]

3. We've got a few different gates in our onboarding, so we should be doing "Just In Time" tutorials. This page is good at sign in (and import). After recording we'll explain the upload process for the first time. When loading the Viewer for the first time, we'll explain the Viewer and comments. When opening devtools for the first time, we'll explain setting log points. It's better to have simple, contextual notes per screen than putting it all in a big thing up front people will skip.

**Comment by jasonLaster** [comment]
Gosh! There's so much I love about this ❤️ 

This feels like a great example of set the foundation and then build.  The foundation feels like add a welcome page and a default new tab and then come back and layer in a proper getting started flow.

**Here's my proposal:**

1. Welcome page has a nice hello and sign in button
2. New tab opens the library

Obviously both could be better, but you've got to start somewhere :)

**Welcome UI**
I love the simplicity of your design. I probably would just add our logo above the header.

1. Header: Welcome to Replay
2. Sub Header: A new way to record and debug websites
3. CTA: Sign In

**Comment by ryanjduffy** [comment]
I wish I could take credit for anything but the screenshot is just the default FF welcome page with FF replaced with Replay :) That said, I'm happy to borrow from what's already there. Going to sketch out a couple ideas and share back soon.

**Comment by ryanjduffy** [comment]
What do you all think of using a "getting started website" for the first recording? Seems like it'd be great to have a button in the welcome flow that was "create your first recording" that opened a new tab and actually started a recording. We could create a mini app that was launched in that tab that provided the first "just in time" tutorial but also included things like some `console.log`'s that would be captured by the recording to help onboard into the devtools side.\

**Comment by jonbell-lot23** [comment]
To echo Jason's point, my preference is to set the foundation and build from there.

But I wouldn't have a new tab open the library, because opening a new tab is the beginning of recording a bug. A new tab should be empty other than a note like "navigate to a site and press record!"

We've talked about the first recording website flow before, and I like it. But I think it comes a bit later once we've set the foundation.

**Comment by jasonLaster** [comment]
Good points Jon! Lets move the discussion for cmd+t New Tab behavior to this issue https://github.com/RecordReplay/gecko-dev/issues/241

**Comment by jasonLaster** [comment]
This is a technical detail, but lets build the welcome page in the DevTools repo. The advantage is that we will 

1. be able to easily edit and avoid deploying a new browser
2. DevTools has auth built in
3. DevTools has our CSS /JS components which will help us be more consistent

**Comment by ryanjduffy** [comment]
I agree that hosting in DevTools would be good. I'm not sure how we'll integrate with the migration tool yet. Still wrapping my head around the coordination logic between the chrome JS and the page JS.

**Comment by jasonLaster** [comment]
I think we can keep migrations separate

**Comment by ryanjduffy** [comment]
With #387 merged, I think we can call this done and address the complete onboarding flow in a separate ticket.
