### ISSUE TITLE
Add Recording upload error ui

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#368]
We currently have a pretty ugly ui when the upload failed. We could do better :)

![118536521-b0430f80-b700-11eb-8302-d48493d00877](https://user-images.githubusercontent.com/254562/118567325-72f37780-b72a-11eb-9b9d-6ff06519f4a8.png)

**Comment by jasonLaster** [comment]
I believe we now show the blue recording id message when the metadata failed. 

I wonder if we want to redirect them to a new URL for failed uploads and of course track the error in honeycomb


Here's the recording that failed `684dec5b-e760-427d-83aa-b55763275109`

<img width="684" alt="Screen Shot 2021-05-21 at 3 03 00 PM" src="https://user-images.githubusercontent.com/254562/119203153-3e8ffc00-ba47-11eb-83d4-be96823eeb51.png">

<img width="970" alt="Screen Shot 2021-05-21 at 3 14 16 PM" src="https://user-images.githubusercontent.com/254562/119203145-3b950b80-ba47-11eb-9ea7-a96930896360.png">

**Comment by ryanjduffy** [comment]
There is still one path that will use the `about:replay` error screen if the recording is unusable. We could probably style it similarly or pass the failure case onto devtools to display. The trend seems to be to the latter.

**Comment by jasonLaster** [comment]
Yep - i think it would probably be best to have an error screen in devtools. It's good to be cross-runtime as well

**Comment by ryanjduffy** [comment]
Should be fixed by #405 and recordreplay/devtools#2762 and recordreplay/website#108

**Comment by jonbell-lot23** [comment]
So can we close this item, @ryanjduffy ?

**Comment by ryanjduffy** [comment]
There are PRs for all the parts but they haven't all landed so I was waiting for that to close this.

**Comment by ryanjduffy** [comment]
All of the PRs have (finally) landed! 🚀
