### ISSUE TITLE
Add preference for recording all tabs

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#377]
When recording using playwright we record all tabs using the RECORD_ALL_CONTENT environment variable.  We should have a preference to enable this for people using the browser directly as well --- instead of the record/replay button there would be a "save" button which saves the current tab's recording.  Having the preference will allow testing this new UX and seeing how it compares to the existing one.

**Comment by bhackett1024** [comment]
The associated PR creates this preference, which should be good enough for testing with.  If we decide to go this route we'll want to make some refinements though.  Some questions:

* When do we want to upload recording data?  Uploading all recording data from all tabs could hurt network performance and make it slower to upload recordings which the user is actually interested in.  We could upload recording data only from the current tab, or not upload at all until the user saves the recording (though that will hurt the developer recording experience).

* When do we want to switch to a new content process when navigating?  When testing I noticed that switching to a new site via the URL bar doesn't switch to a new content process, so the resulting recording will retain that tab's entire history, which doesn't seem right.  We could switch to a new content process when navigating this way, but it's a grayer area when e.g. clicking on a link --- it seems there we wouldn't want to switch to a new process in all cases, e.g. the link target has the same origin.

**Comment by jasonLaster** [comment]
Thanks @bhackett1024 

I opened #379 to discuss this new flow. With your second question, do you think we want the same or different behavior if we're always recording?

**Comment by bhackett1024** [comment]
I don't know about same vs. different, these are two different flows and we should be able to decide on what we want their behavior to be without consideration for the other.  At some point we'll need to pick one of the flows as the default and maybe remove the other one.

**Comment by bhackett1024** [comment]
This is working now in the latest browser.
