### ISSUE TITLE
"Always On" UX

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#379]
Now that is possible to begin experimenting with an "always on" UX where users do not need to press the record button to start recording, there are some UX questions:

### When do we want to upload recording data? 
Uploading all recording data from all tabs could hurt network performance and make it slower to upload recordings which the user is actually interested in. We could upload recording data only from the current tab, or not upload at all until the user saves the recording (though that will hurt the developer recording experience).

### When do we want to switch to a new content process when navigating? 
When testing I noticed that switching to a new site via the URL bar doesn't switch to a new content process, so the resulting recording will retain that tab's entire history, which doesn't seem right. We could switch to a new content process when navigating this way, but it's a grayer area when e.g. clicking on a link --- it seems there we wouldn't want to switch to a new process in all cases, e.g. the link target has the same origin.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-41](https://linear.app/replay/issue/RUN-41/always-on-ux)
