### ISSUE TITLE
Include recording driver in distribution

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#381]
Currently on first start we download the latest version of the recording driver to the user's app data folder, and occasionally keep it updated separately from the browser's normal auto update process.  This works fine when users need to manually initiate recording, but when recording all tabs we should have the driver available initially so that all content processes the browser creates can use that driver.  This requires including the driver in the packaged distribution, in a place where ContentParent knows to look.

This will be needed if we make the always-record mode (#377) the default.

**Comment by bhackett1024** [comment]
Oh, and we avoid this when running playwright by having the playwright scripts download both the browser and the recording driver and configure the browser with the driver path to use via the environment.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-202](https://linear.app/replay/issue/RUN-202/include-recording-driver-in-distribution)
