### ISSUE TITLE
Cannot start recording

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#383]
starting a recording results in a white screen. It looks like this is happening because we cannot find a browser for that pid.

https://github.com/RecordReplay/gecko-dev/blob/webreplay-release/devtools/startup/DevToolsStartup.jsm#L1793-L1803

![getBrowserPid](https://user-images.githubusercontent.com/254562/119206479-1f499c80-ba50-11eb-82f0-c7ecf5c5c30f.png)

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-43](https://linear.app/replay/issue/RUN-43/cannot-start-recording)
