### ISSUE TITLE
Replay showing white screen on very simple HTML page

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#400]
This is my source code:

```
<script>
console.log("init");

var i;
for (i = 0; i < 1001; i++) {
  console.log('loop');
}
</script>
This is a simple page doing a big ass loop.
```

It loads fine in Replay, but when I press the record button the page goes white. The Replay itself seems to be blank.

I theorised that maybe it was a space in my URL causing this, but I removed the space and the problem persisted.

https://share.descript.com/view/CGNENAV4pp9

**Comment by jasonLaster** [comment]
@jonbell-lot23 could you create a glitch or codesandbox?

**Comment by jonbell-lot23** [comment]
Here's a codesandbox: https://codesandbox.io/s/confident-roentgen-94g3w?file=/index.html

**Comment by ryanjduffy** [comment]
Seems to work now so closing this out

https://app.replay.io/recording/3f11775e-db25-4e28-bf21-db706ab73861
