### ISSUE TITLE
Upload screen stalls, but Replay is ready

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#401]
Screen stalls indefinitely after recording/upload, but the Replay is live. (Even though I didn't give it permission to be live, which is a security/privacy issue)

Here's a video of me experiencing the issue:
https://share.descript.com/view/7eZa2qWFx1H

Here's the Replay: https://replay.io/view?id=0229f0bb-55b0-4bee-96db-e797057054fc

**Comment by ryanjduffy** [comment]
Guessing this is too old to repro any longer so going to close :)
