### ISSUE TITLE
backspace key will navigate to the previous page

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#411]
> is there a way to use the backspace keystroke without going back a page?
> 
> so in the replay browser, if i ever hit the backspace key, it brings me to the previous page and for our app, when i hit backspace, that key is supposed to delete numbers in a grid

**Comment by jasonLaster** [comment]
This reproduces if you go to a website like nytimes.com, click a link and the press the back button

**Comment by jasonLaster** [comment]
https://user-images.githubusercontent.com/254562/121263446-792ccd80-c86a-11eb-94d8-d942f0b75f6c.mov

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-207](https://linear.app/replay/issue/RUN-207/backspace-key-will-navigate-to-the-previous-page)
