### ISSUE TITLE
Investigate speeding up creating the recording tab

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#416]
**Description:**

We should look to see if there's anything we can do to improve the actual or perceived performance of starting a recording.

> everytime when I press the "Record" button, there is a delay of like 3-4 seconds before I can start doing the testing steps(that's because the website I'm testing refreshes when the "Record" button is pressed). That's a bit annoying because also the first 3-4 seconds of the video created shows a white screen with a loading state.

**Comment by loganfsmyth** [comment]
This seems pretty much the same as https://github.com/RecordReplay/gecko-dev/issues/352
