### ISSUE TITLE
The replay.io/view page fails to replay after recording.

### ISSUE THREAD

**Issue by kannanvijayan** [replayio/gecko-dev#417]
Here's a recording of the replay.io/view page (and clicking on settings pane), that fails to replay:

https://replay.io/view?id=6f63081e-a1b7-4643-9156-d73d0108db14

I've generally had trouble getting the library view to record and replay.  Also, the page itself was very slow when this recording was being made.

**Comment by ryanjduffy** [comment]
@kannanvijayan is this too old to bother with or do we need more follow up on recording/replaying the library view?

**Comment by kannanvijayan** [comment]
Let me try to make this recording again and see if it's still a problem.

**Comment by ryanjduffy** [comment]
Closing assuming it's no longer an issue. #biasforaction 😀
