### ISSUE TITLE
Microphone Not Available

### ISSUE THREAD

**Issue by seanaguinaga** [replayio/gecko-dev#423]
![image](https://user-images.githubusercontent.com/15254340/122837967-e8aeae00-d2a9-11eb-81c3-0a36fd72523b.png)
 returns false always in recording mode

https://replay.io/view?id=ecfe4ff3-49ef-4ef2-8caf-ecfd3557f729

vap-canvas.netlify.app/tab3

**Comment by ryanjduffy** [comment]
Relates to #56

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-209](https://linear.app/replay/issue/RUN-209/microphone-not-available)
