### ISSUE TITLE
The replay tab takes awhile to appear

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#424]
I've found that occasionally the first replay that I make can take awhile to appear which can be confusing

STR:
1. Open replay browser
2. click record
3. do stuff
4. click stop

wait for the replay tab to appear. can take 15-30 seconds, but should appear immediately.

**Comment by jonbell-lot23** [comment]
This is a great repro case. The tab takes *forever*:
https://share.descript.com/view/keBe4i38pWs

And then the Replay itself is loading very very slowly (or maybe it's failing outright?):
https://replay.io/view?id=26d1f921-5830-459f-9e1a-7b573da39910

**Comment by ryanjduffy** [comment]
We have the spinner and some telemetry around this so I'm going to close this and we can reopen or open a new one with more actionable steps.
