### ISSUE TITLE
Hide the Mozilla VPN page

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#426]
<img width="1637" alt="Screen Shot 2021-06-23 at 1 27 46 PM" src="https://user-images.githubusercontent.com/254562/123300843-d44bfa80-d4cf-11eb-890f-d256d97426ac.png">

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-50](https://linear.app/replay/issue/RUN-50/hide-the-mozilla-vpn-page)
