### ISSUE TITLE
"Launch Replay" button lands you on "replay:library," which is a blank page

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#429]
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/9154902/123504200-eaaead80-d6ab-11eb-9eb3-d188d867d62c.png">

Replay launched, which is great. But I'm getting sent to a blank page, as shown here.

**Comment by jonbell-lot23** [comment]
Same for logged in states:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/9154902/123504279-46793680-d6ac-11eb-8ada-1781475739dc.png">

**Comment by ryanjduffy** [comment]
This appears fixed in the browser as of this morning.
