### ISSUE TITLE
Upload source maps when saving recordings to disk

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#435]
Currently, source maps will be uploaded when using playwright and configuring it to upload all recordings using the RECORD_REPLAY_SERVER environment variable.  When recordings are being saved to disk and uploaded later they won't contain any source maps, however.  It would be nice to save source map information to ~/.replay in the latter case and upload them along with the recording itself in the replay-recordings CLI tool.

**Comment by ryanjduffy** [comment]
This mentions playwright and the CLI so wanted to verify this issue is in the right place. Is there gecko work to do or should we move this to another repo?

**Comment by bhackett1024** [comment]
This might be good for the ops repo.  The problem is that we don't have a defined strategy for how users should get their source maps to us.  The status quo might be good --- the browser uploads source maps when explicitly recording, but otherwise they have to be uploaded separately as part of the build process --- but we need to write out that approach and agree on it.

**Comment by ryanjduffy** [comment]
Makes sense. Thanks! I'll create a new one there (since GH won't let us move from public to private).
