### ISSUE TITLE
iPad Air site not looking right -- canvas issues?

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#439]
1. Go to https://www.apple.com/ipad-air/ and record with Replay
2. Notice the strange visual flubs: 
<img width="360" alt="image" src="https://user-images.githubusercontent.com/9154902/124862499-98558100-e009-11eb-82d3-0bf1408c3494.png">

3. Check how it looks in the replay: https://app.replay.io/?id=2e6e30f0-f0eb-48e1-9bae-a1072dc4c124&point=76261860111285211039325359462942164&time=27104&hasFrames=false

**Comment by ryanjduffy** [comment]
The browser reports webGL warnings now which is likely the cause so duping this out to #58
