### ISSUE TITLE
Record user event info as part of the recording

### ISSUE THREAD

**Issue by loganfsmyth** [replayio/gecko-dev#440]
We've been talking about wanting to know what keys were pressed during a recording. Right now we track mousemove/mousedown events and that is it. It would be great to expand that.

Here's a patch from playing around a bit earlier: https://gist.github.com/loganfsmyth/4e598378e16789681ee9620e39233a07

**Comment by jasonLaster** [comment]
It would be great to also track navigation events in the same way.

**Comment by loganfsmyth** [comment]
This is done and the browser build for Mac for keyboard and navigation tracking has been released.
