### ISSUE TITLE
Update "Reconnecting to cloud..." tooltip

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#448]
from @loganfsmyth 

> Cool, yeah I think the tooltip would be clearer if it started as "Connecting to Replay server..." and then eventually switched to "Unable to connect to Replay server..." after X amount of time. It sits there retrying every 3 seconds right now so either way it will reconnect, but once we've tried and failed a few times it's probably nice to hint to the user that something has gone wrong

from @jonbell-lot23 

> I’m supportive of that, although maybe a touch shorter
“Connecting…”

I believe the proposal is to update the tooltip to first ready `Connecting...` and then after a couple of seconds `Could not connect`.

**Comment by jasonLaster** [comment]
If it's easy to do a custom tooltip, it might also be nice to have a link to docs. That way we can mention VPNs, our support@replay.io and discord channel.

This is also something that we should make sure we have telemetry for

**Comment by ryanjduffy** [comment]
When is this message displayed? Is this ticket still relevant?

**Comment by jasonLaster** [comment]
it's shown when we cannot connect to the dispatcher

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-212](https://linear.app/replay/issue/RUN-212/update-reconnecting-to-cloud-tooltip)
