### ISSUE TITLE
Services.prefs fails when fetching replay.* preferences

### ISSUE THREAD

**Issue by joebobmiles** [replayio/gecko-dev#456]
After getting Replay up and running on Windows, I've been working on tracking down the errors that occur when attempting to start a recording. The only error that triggers when the button is clicked is a failure in `pingTelemetry` in `devtools/server/actors/telemetry.js`. Specifically, it's on line 6, where `pingTelemetry` attempts to get the telemetry URL by calling `Services.prefs.getStringPref("replay.telemetry.url")`. When it does so, the following error is emitted:

```
Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getStringPref]
```

I tried poking similar preferences, such as "replay.telemetry.enabled" and got the same error everytime. However, when I checked other Replay and non-Replay preferences, such as "devtools.recordreplay.recordingsURL", I got the expected preference values listed in about:config.

Is this old code or is something missing from the Replay runtime that registers those missing preferences?

**Comment by loganfsmyth** [comment]
This is likely because you have not set up a `mozconfig` file. We have samples for linux and osx but it doesn't look like the branch has one for windows. If you create one manually that has the stuff common between OSX and linux, it'll definitely help.

https://github.com/RecordReplay/gecko-dev/blob/windows-port/mozconfig.macsample

**Comment by joebobmiles** [comment]
Exactly what I needed, thanks Logan!

EDIT:
Config that worked for me:
```
. $topsrcdir/browser/config/mozconfig

mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/rr-opt
mk_add_options MOZ_MAKE_FLAGS="-j12"
mk_add_options AUTOCLOBBER=1

ac_add_options --with-branding=browser/branding/recordreplay
ac_add_options --with-app-name=replay
ac_add_options --with-app-basename=Replay
ac_add_options --enable-replace-malloc
ac_add_options --disable-sandbox
```
