### ISSUE TITLE
Logging in to Replay browser should take me back to the page I was on

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#462]
1. I was on foo.com
2. I went to record but I needed to log in first

Expected:
1. After login, I should be at foo.com

Actual:
1. After login, I ended up at Replay's library

**Comment by ryanjduffy** [comment]
Couple possible approaches:

* Clicking Sign In opens a new tab (if you're not on app.replay.io or about:blank) to log in
* Wait for #518 which should sidestep this issue
* Add redirect logic to return the user back to their source page. This feels a bit weird to me to go through replay's auth flow and then land on a non-replay site.

I think implementing 1 now should be easy and an improvement but that 2 is the full credit answer.

**Comment by jasonLaster** [comment]
Yep - one feels fine.

**Comment by ryanjduffy** [comment]
Closing this since we've landed option 1 and have another ticket for popping a window to auth outside of Replay
