### ISSUE TITLE
Issue establishing a connection with the replay server

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#463]
Jon at Zyspy is seeing an issue when starting a new recording with Replay

**Comment by jasonLaster** [comment]
Here's the error screen with `No Such Channel`

![image](https://user-images.githubusercontent.com/254562/129619212-ef9b4845-894b-43d3-b50a-5bf78b4ec316.png)

**Comment by jasonLaster** [comment]
Looks like the issue might be with `High Sierra (10.13.6)`

**Comment by jasonLaster** [comment]
we should attempt to log most if not all of replays exceptions to telemetry so we can see when our users are affected.

Our `No Such Channel` error comes from within `gecko-dev` https://github.com/RecordReplay/gecko-dev/blob/webreplay-release/toolkit/actors/WebChannelParent.jsm#L49-L57. 

We might be able to catch this error on the devtools side here though and log an error to telemetry https://github.com/RecordReplay/devtools/blob/master/src/ui/utils/browser.ts#L3-L10

We might be able to catch it when the channel is setup to wherever `new WebChannel("record-replay")` is happening

**Comment by ryanjduffy** [comment]
I have a branch up to add telemetry for these failures. I think this might be a regression from #451 which changed the name of the channel in gecko-dev but didn't update the frontend.

https://github.com/RecordReplay/gecko-dev/commit/281613e5e05ac13bfa49d0d38de457c50b4642c7#diff-de308cf37bb1e668846a73397a262eb5888c9c490a74b236e97f772d236146ecR748

@loganfsmyth - wdyt?

**Comment by ryanjduffy** [comment]
Well, it's just one place that wasn't updated. The token channel msg was updated but `setUserInBrowserPrefs` still passes the user via `record-replay` which isn't handled by gecko.

**Comment by loganfsmyth** [comment]
`setUserInBrowserPrefs` was left in for backward-compat for users still using old build of the browser. At some point we can remove it, but I don't see any reason to rush. "No Such Channel" is just the browser letting you know it got a a message for a channel that doesn't exist, but it's expected that the channel doesn't exist.

**Comment by ryanjduffy** [comment]
Thanks @loganfsmyth. Do we capture usage stats on the browser versions we have out so we can decide when to remove these sorts of compatibility debt?

**Comment by loganfsmyth** [comment]
We don't as far as I'm aware, we're just been making the decision to drop support for old builds some time after the previous ones were released.

**Comment by loganfsmyth** [comment]
But also we haven't had to make breaking changes to the browser APIs very often, usually we end up just making additive changes.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-53](https://linear.app/replay/issue/RUN-53/issue-establishing-a-connection-with-the-replay-server)
