### ISSUE TITLE
Investigate performance of page load when starting recording.

### ISSUE THREAD

**Issue by kannanvijayan** [replayio/gecko-dev#466]
Get an idea of _what_ are the causes of page-load being slow when starting a new recording, and _how much_ it affects performance.

**Comment by jasonLaster** [comment]
Runnables:

`maybeInitializeFrameLoader --> createBrowser --> getNewOrUsedBrowserProcess` 💣

**Comment by kannanvijayan** [comment]
More detailed notes here: https://www.notion.so/replayio/Perf-Measurement-ec7f0776c0004b58abcb9065ab881886

**Comment by kannanvijayan** [comment]
Closing this - as the investigation identified where the new-browser-process creation time affects the responsiveness of creating a new recording tab.
