### ISSUE TITLE
Unexpected Socket error shown for old tabs

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#468]
It looks like tabs that i leave for awhile have this error screen in Replay, but show the Are You There in chrome

<img width="1552" alt="Screen Shot 2021-08-22 at 4 46 06 PM" src="https://user-images.githubusercontent.com/254562/130369622-33e31153-bd8f-4899-b9a4-fde4e68fe053.png">

**Comment by jasonLaster** [comment]
We should not show this warning if the devtools has been inactive for more than a couple of minutes...

**Comment by hbenl** [comment]
I got the "Are you still there?" modal in the Replay browser when I left a replay open for a while, so I don't think this is a browser issue. It seems that a closed socket will sometimes emit a `close` event and sometimes an `error` event.

> We should not show this warning if the devtools has been inactive for more than a couple of minutes...

This is implemented in RecordReplay/devtools#3761
