### ISSUE TITLE
Add the element being clicked as metadata for the event sidepanel mouse click events

### ISSUE THREAD

**Issue by jaril** [replayio/gecko-dev#473]
Follow up from RecordReplay/devtools#3307.

Add the element being clicked as metadata to a click event, e.g. `Mouse Click button.my-button`

**Comment by jasonLaster** [comment]
I'm pretty sure that @loganfsmyth said that this was not possible the way we are gathering the event clicks

**Comment by bhackett1024** [comment]
"not possible" is pretty strong, but we do need gecko-dev changes to figure out which element each click is targeting (and similarly, info about the active element text is being entered into), and convey that to the driver and then the protocol.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-55](https://linear.app/replay/issue/RUN-55/add-the-element-being-clicked-as-metadata-for-the-event-sidepanel)
