### ISSUE TITLE
Crash not shown in about:crashes

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#474]
I just had a crash that did not show up in `about:crashes`. 

1. should it?
2. did we receive it in our backend?

<img width="1283" alt="Screen Shot 2021-08-27 at 10 01 48 AM" src="https://user-images.githubusercontent.com/254562/131139783-cd7b4f4e-c85a-47e2-8868-6807aa598620.png">
<img width="1283" alt="Screen Shot 2021-08-27 at 10 01 31 AM" src="https://user-images.githubusercontent.com/254562/131139785-c97c836c-e114-4272-824f-1b7fc2bfc251.png">

**Comment by bhackett1024** [comment]
Per https://github.com/RecordReplay/triage-dashboard/blob/master/index.md we have several crash reports from the recorder in the last day, and one from gecko-dev.  Since it's not showing up in about:crashes though this isn't a gecko-dev report.

**Comment by bhackett1024** [comment]
On closer look, the recorder crash reports are all associated with windows, and the gecko-dev report is from earlier than the point where you had the crash.

https://github.com/RecordReplay/ops/issues/134 is the best way to see how often this is affecting people (send a telemetry report when showing the tab crashed screen) and start understanding why we're not getting actual crash reports here.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-56](https://linear.app/replay/issue/RUN-56/crash-not-shown-in-aboutcrashes)
