### ISSUE TITLE
Unexpected recording error (connection has not been authenticated)

### ISSUE THREAD

**Issue by kannanvijayan** [replayio/gecko-dev#482]
Jason and I noticed this on the morning of Aug 30.  

![image](https://user-images.githubusercontent.com/76070462/131367198-6fbab80f-97a0-4927-9031-d97c80d7302c.png)

**Comment by loganfsmyth** [comment]
I'm going to close this for now. If we still see this after Kannan's process-cache patches have been released, let's reopen.
