### ISSUE TITLE
Restart precached browser processes periodically

### ISSUE THREAD

**Issue by kannanvijayan** [replayio/gecko-dev#488]
This is to resolve issues with API keys being issued to precached browser processes, and becoming stale while the parent process renews its keys.

**Comment by loganfsmyth** [comment]
Probably most importantly, we'll need some way to explicitly invalidated the cached process if the auth token expires.

**Comment by kannanvijayan** [comment]
Where in the browser do we fetch and install a new auth token?  I assume it happens in the parent process.  I don't think it would be too difficult (cross fingers) to call into the preallocated process manager from there and trigger a full invalidation and restart.

**Comment by loganfsmyth** [comment]
Around here: https://github.com/RecordReplay/gecko-dev/blob/338665d92b8a2264d4764d90746727132fbcd430/devtools/server/actors/replay/connection.js#L317
