### ISSUE TITLE
Select dropdown is not shown

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#494]
This is what it should look like
![](http://g.recordit.co/YCKFvASRxc.gif)

Here is a replay where the dropdown should be shown
https://app.replay.io/recording/b2b4dd71-0c94-4cfc-9c40-5f8aa6b88190?point=26610521430522996687218165111855639&time=14169&hasFrames=false

Here is the codesandbox where you can try clicking on the dependency dropdown
http://recordit.co/YCKFvASRxc

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-58](https://linear.app/replay/issue/RUN-58/select-dropdown-is-not-shown)
