### ISSUE TITLE
React DevTools Shell does not work while recording

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#504]
The react devtools shell loads the sample app normally, but when recording the sample app script fails to loads.

The reason for this is that the injected script has a caching issue where it needs a hard-refresh which clears the cache and when we click the record button it uses the cache.

Here's a loom with the problem
https://www.loom.com/share/bc64c48abb634402b046893f7d55471d

Here's the contributing guide to reproduce the problem:
https://github.com/facebook/react/blob/main/packages/react-devtools/CONTRIBUTING.md

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-222](https://linear.app/replay/issue/RUN-222/react-devtools-shell-does-not-work-while-recording)
