### ISSUE TITLE
Update Recording button look

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#507]
We should do a quick visual refresh of the recording button for both the light and dark version of the replay browser

This blue/red is not ugly, but it can certainly be improved

<img width="261" alt="Screen Shot 2021-09-08 at 6 45 16 PM" src="https://user-images.githubusercontent.com/254562/132608773-5d5e70b6-702d-46be-91d7-f475c3b1d4f3.png">

<img width="314" alt="Screen Shot 2021-09-08 at 6 49 30 PM" src="https://user-images.githubusercontent.com/254562/132608813-447231e4-e713-49ca-9e3c-d161aff6e905.png">

<img width="159" alt="Screen Shot 2021-09-08 at 8 13 08 PM" src="https://user-images.githubusercontent.com/254562/132616364-57291e94-fb47-4233-9b1c-46ed5931397c.png">
<img width="209" alt="Screen Shot 2021-09-08 at 8 13 06 PM" src="https://user-images.githubusercontent.com/254562/132616366-5a4306b3-cdf7-4890-ae90-32a9d8e23d5f.png">
<img width="210" alt="Screen Shot 2021-09-08 at 8 12 58 PM" src="https://user-images.githubusercontent.com/254562/132616368-35d5420f-f78a-47af-925d-1146c37b686d.png">

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-64](https://linear.app/replay/issue/RUN-64/update-recording-button-look)
