### ISSUE TITLE
Replays with canvas drawing are very large

### ISSUE THREAD

**Issue by schani** [replayio/gecko-dev#508]
This took a long time to upload, despite being less than a minute long, with very little user interaction:

  https://app.replay.io/recording/c957bbe7-4652-4ac8-9844-51656a15dfb1

Feel free to make your own at

  https://staging.heyglide.com

You'll need to do "New App" and then pick a Google Sheet.

**Comment by schani** [comment]
This one also takes a long time to upload, and there shouldn't be much going on, in particular no canvas drawing: https://app.replay.io/recording/da9b10d1-8e4d-461f-ad79-e07eaa8ec7f5

**Comment by kannanvijayan** [comment]
Thanks @schani.  To add info to the bug:

The recording (c957bbe7-4652-4ac8-9844-51656a15dfb1) is 177Mb large.  It'd be worthwhile to go through and figure out where the volume is coming from and what we can do about that.

@schani I'm guessing when you click the google sheet it uses the sheet as a source but uses the glide data viewer to display it?

Edit:
da9b10d1-8e4d-461f-ad79-e07eaa8ec7f5 is ~42Mb.
c957bbe7-4652-4ac8-9844-51656a15dfb1 is ~177Mb.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-225](https://linear.app/replay/issue/RUN-225/replays-with-canvas-drawing-are-very-large)
