### ISSUE TITLE
The connection has not been authenticated

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#510]
- I saw it after Replay had been open (and unused for an hour or two)
- I logged out and logged in and still saw the problem
- I quit and re-opened Replay and the problem was fixed

<img width="764" alt="Screen Shot 2021-09-06 at 9 24 03 PM" src="https://user-images.githubusercontent.com/254562/132769084-17f3582b-34e9-4bdc-9436-7b38ca1cd7e2.png">

**Comment by jasonLaster** [comment]
This might be obvious to others, but I think the problem is that at some point the JWT expires and because app.replay.io is not open to check, the browser does not realize it expired until the user tries to hit save. 

The browser should be able to ping the backend regularly to see if it is still authenticated and if at some point it is not, switch the button to sign in.

Even better would be to silently re-authenticate, but that might be difficult without the auth0 logic we have in app.replay.io

**Comment by loganfsmyth** [comment]
The browser itself has logic that is supposed to change to the unauthenticated state once the JWT expires. Maybe something is wrong with that logic.

**Comment by loganfsmyth** [comment]
https://github.com/RecordReplay/gecko-dev/blob/251fdaf2afd8697875f31c4253fb3c98aa122f3e/devtools/server/actors/replay/connection.js#L318

**Comment by loganfsmyth** [comment]
Alright, the logging patches are deployed so when this happens again we can at least have a better sense of why.

**Comment by loganfsmyth** [comment]
Closing since #558 is closed now. Guess we can keep an eye out.
