### ISSUE TITLE
Nextjs does not include the basepath in the sourceMappingUrl

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#511]
This PR successfully gets NextJS to create sourcemaps which are adjacent to the JS, but fails to create a sourceMappingUrl that can be found by chrome or replay devtools.

https://github.com/statelyai/xstate-viz/pull/261

It would be nice to figure out what went wrong and update our documentation
https://www.notion.so/replayio/Source-Maps-aa12f23cb77b4c40ad37ab5836ad17be

**Comment by jasonLaster** [comment]
By the way, this is where `productionBrowserSourceMaps` is set in NextJS's webpack config
https://github.com/vercel/next.js/blob/cab846481db9645c686f25b1a505fd9e0cba1dd2/packages/next/build/webpack-config.ts

**Comment by Andarist** [comment]
> It would be nice to figure out what went wrong and update our documentation

OTOH - shouldn't this just work by default in Chrome? This is exactly what Next recommends in their docs: https://nextjs.org/docs/advanced-features/source-maps . So if this is not enough for Chrome then, if I understand correctly, Next docs should mention additional steps to make this work.

**Comment by jasonLaster** [comment]
Agreed, this issue should probably be in the NextJS repo. I filed this sibling bug report
https://github.com/vercel/next.js/issues/28976
