### ISSUE TITLE
Replay Browser crahsed

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#512]
Bug Report from Santiago at Glide

Hey Guys! Yesterday, Replay kept saying that an error had occurred. So I closed it and restarted several times. After the 5th time, give or take, it started to work but I started to notice that my laptop was overheating really badly. It was until I tried to close Replay one more time that the whole thing crashed and cause the laptop to restart. I haven't open it today at all and my laptop is back to normal.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-66](https://linear.app/replay/issue/RUN-66/replay-browser-crahsed)
