### ISSUE TITLE
Browser reports a security warning with app.replay.io

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/gecko-dev#514]
![LtFqXvjc](https://user-images.githubusercontent.com/788456/133481171-308d880f-8865-4b10-88d7-3890e3cac1e0.jpg)

**Comment by jasonLaster** [comment]
@ryanjduffy can you follow up and get more information?

**Comment by gideonred** [comment]
Another report that's consistent, the following site (online.capitalcube.com/login) works in Chrome, but doesn't work in Reply:
![](https://cdn.discordapp.com/attachments/869029659751350293/890637320431231047/Screen_Shot_2021-09-23_at_12.34.03_PM.png)

I haven't testing Firefox yet, will do so next.

**Comment by gideonred** [comment]
Firefox is showing the same problem:
<img width="1348" alt="Screen Shot 2021-09-23 at 1 02 57 PM" src="https://user-images.githubusercontent.com/28845582/134551799-ce077734-ae9f-4a5b-ba39-a3bc74f932b8.png">

**Comment by ryanjduffy** [comment]
This latest case might be because that server's cert has too long of an expiry duration.

![image](https://user-images.githubusercontent.com/788456/134553280-0a348d72-a1c0-4c67-90e3-003d103b1cbd.png)

> 3. Certificate lifetime greater than 398 days
> Earlier this year, to ensure a secure web environment to the user, CA/B Forum, decided to limit the lifespan of all newly > issued certificates to 398 days. Starting from September 1st, 2020, all the major browsers (Google Chrome, Mozilla > > Firefox, and Apple Safari) will reject certificates issued after this date with a validity period of more than 398 days.

from https://sematext.com/blog/ssl-certificate-error/

**Comment by gideonred** [comment]
O wow, great find!!

We should probably start some kind of documentation on our attitude towards Firefox bugs/behaviors. The simple attitude is to say: "It's a Firefox thing, won't fix", but we should probably put more thought into it.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-68](https://linear.app/replay/issue/RUN-68/browser-reports-a-security-warning-with-appreplayio)
