### ISSUE TITLE
Support "replay:record" protocol URLs on Debian

### ISSUE THREAD

**Issue by tux3** [replayio/gecko-dev#515]
Hello, I unzipped linux-replay.tar.bz2 and started `./replay` for the first time (Debian bookworm on Linux 5.13).  
I'm a Firefox user, so I clicked the "import my settings" button, logged in, and went on to the demo.

When starting the 'back to the future' demo, replay opened a tab to `replay:record?url=https://static.replay.io/demo`, however I get the following error:

![snap-767](https://user-images.githubusercontent.com/5155966/133480860-45071ea8-be38-4e5f-b609-7cf12e6cbbb8.jpg)

I looked in about:config at the protocol handlers, but I don't see one for `replay`. Here's the results when I search for `replay`:

![snap-768](https://user-images.githubusercontent.com/5155966/133481278-0f36051f-40af-4d5f-9c73-40e7b25dc32f.jpg)

Apologies if I missed something obvious =)

**Comment by jasonLaster** [comment]
Thanks for sharing @tux3! `replay:` is our url scheme which definitely works on the mac, but we likely missed something for Debian. This write up is a huge help

**Comment by jasonLaster** [comment]
@hbenl @joebobmiles does the "Launch Replay" button work for you on other Linux versions? Wondering if we should hide the Launch button in the library for some of these cases until we add proper support.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-69](https://linear.app/replay/issue/RUN-69/support-replayrecord-protocol-urls-on-debian)
