### ISSUE TITLE
Streamed HTML source isn't shown incrementally by replay

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/gecko-dev#519]
If a site is streaming a large html file over time, the HTML source in Replay only displays the final state and not the incremental state as it loads. That means that if the user sets breakpoints on inline scripts, the source panel will show the entire source even if part of the source hadn't been downloaded at the time the script was evaluated.

**Comment by jasonLaster** [comment]
Moving to Gecko Dev because this is not frontend related and is likely Gecko specific.

**Comment by jasonLaster** [comment]
@ryanjduffy out of curiosity, how did you find this?

**Comment by ryanjduffy** [comment]
I might be mistaken on this, actually. I diagnosed by logging `document.querySelectorAll(...).length` in a replay with a large streamed html and it was reporting the same number. However, I think I was looking for the wrong selector and I'm not sure there's actually a bug here after all. Still looking into it.

**Comment by ryanjduffy** [comment]
I was misunderstanding the reported problem it seems. The question was why does the source view of the HTML file show the complete results when pausing on a breakpoint mid-download.

The Elements panel (which the user didn't have enabled) does show the expected content but the Source view does not. I can understand the question but I'm not sure how well it maps to the typical replay use case. I'm curious what others think on the utility of showing incremental source files.

At most, it would be an opt in view, I think, since it could be confusing for those that expected the full source so they could set a breakpoint at a later time.

**Comment by ryanjduffy** [comment]
Closing as "Will not implement" under the assumption that the Elements panel will be sufficient to track the current DOM state of streamed HTML
