### ISSUE TITLE
SMAE fails to replay

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#520]
1. go to https://smae.surge.sh/
2. press new game

**Comment by jasonLaster** [comment]
https://app.replay.io/recording/afedb00c-0d7b-4f73-a92f-0f2213ed57cc
https://app.replay.io/recording/571a60ab-e6e1-4bb0-904e-b6c06b58c10f

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-70](https://linear.app/replay/issue/RUN-70/smae-fails-to-replay)
