### ISSUE TITLE
Send crash data with tab crashes

### ISSUE THREAD

**Issue by kannanvijayan** [replayio/gecko-dev#521]
Tab crashes sent with `pingTelemetry` don't package crash data.  We should do so.

**Comment by gideonred** [comment]
Adding this to our Customer Support board, as this will help improve the following Customer facing metric: https://ui.honeycomb.io/replay/datasets/backend/result/4quDRsvLBTq/a/FLQVs2hyx6t/Browser-Tab-Crashes
