### ISSUE TITLE
Wrong frame scrubbing behavior

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#526]
STR:

1. visit https://app.replay.io/recording/bc9d2aaa-3c82-47f6-b518-75e0a7a496ec?point=42187411994614488438153947465646888&time=18644.928673323822&hasFrames=true
2. scrub around in the frame timeline

The last point in the frame is a console.error() call, which is wrong.  This is probably gecko's fault, where it is reporting that the exit point of the frame is at the last breakpoint site rather than something more sensible like the function's closing brace, but it would be good to be sure.

**Comment by loganfsmyth** [comment]
This code is minified, which is part of why it's behaving so poorly. The actual code that runs is
```
function C(e) {
  g += e.data.length;
  const t = JSON.parse(e.data);
  if (t.id) {
    var n, r;
    const {
      method: e,
      resolve: o,
      reject: i
    } = f.get(t.id);
    null === (n = window.performance) || void 0 === n || n.mark(`${e}_end`), null === (r = window.performance) || void 0 === r || r.measure(e, `${e}_start`, `${e}_end`), f.delete(t.id), t.error ? (a.warn("Message failed", e, t.error, t.data), i(t.error)) : o(t.result)
  } else E.has(t.method) ? E.get(t.method)(t.params) : a.error("Received unknown message", t)
}
```
and that is prettified. In the actual source is more like this all on one line
```
else E.has(t.method)?E.get(t.method)(t.params):a.error("Received unknown message",t)}
```
at the end of the function.

The sourcemap generated here has no mapping for the `}` specifically so the mapping for the `t)` portion of the code does not end and extends through the `}` location as well.

So at the end of the day this is a sourcemap issue.

**Comment by jasonLaster** [comment]
Thanks @loganfsmyth. Do you think it is reasonable to close this?

**Comment by loganfsmyth** [comment]
I don't think there's anything actionable for us unfortunately.
