### ISSUE TITLE
Can't replay cocos creator game preview

### ISSUE THREAD

**Issue by danyadanch** [replayio/gecko-dev#531]
Hey! I wanted to test how replay REPLAYS cocos creator game preview and faced some errors.
If I just open game preview in default mode it works correctly, but if press "REC" button my preview is not loading.

What i see in the console: 
`Uncaught TypeError: cc.logID is not a function`
`Uncaught TypeError: can't access property "init", cc.assetManager is undefined`

What kind of information i can provide to get you better understanding of error?

**Comment by ryanjduffy** [comment]
@danyadanch - Thanks for reaching out. We don't yet support a handful of features including WebGL with Replay so that is my guess as to the root cause. If you can share a link to what you are trying to record, I can take a look and provide a more specific response.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-72](https://linear.app/replay/issue/RUN-72/cant-replay-cocos-creator-game-preview)
