### ISSUE TITLE
WebAssembly is not defined

### ISSUE THREAD

**Issue by jazzdan** [replayio/gecko-dev#533]
If you run this sample code in the Replay browser, which is the first google result for "how to check if a browser supports web assembly", the Replay browser fails the check https://stackoverflow.com/questions/47879864/how-can-i-check-if-a-browser-supports-webassembly. Here's a Replay https://app.replay.io/recording/277cff50-4e00-4c4c-b4f7-e5c11523f3e3 showing that `WebAssembly` is not defined. I'm guessing a lot of WebAssembly projects use this check.

We do support webassembly in other areas, so it's weird that the JavaScript API is undefined. It's possible we inadvertently disabled it and there's an easy win here.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-74](https://linear.app/replay/issue/RUN-74/webassembly-is-not-defined)
