### ISSUE TITLE
CodeSandbox video is incomplete

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#534]
> the video uploaded is incomplete, even some event clicks are missing there, which makes the debugging not helpful

**Comment by loganfsmyth** [comment]
@jasonLaster What video? Seems like this is missing a recording link.

**Comment by jasonLaster** [comment]
Sorry about that, 

here's the recording id: 07dd393f-7f16-4afe-b016-7cff85e660a0
and a loom https://www.loom.com/share/25b10262599648e8adc89a35d86bef08

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-235](https://linear.app/replay/issue/RUN-235/codesandbox-video-is-incomplete)
