### ISSUE TITLE
Replay recording can't load

### ISSUE THREAD

**Issue by Andarist** [replayio/gecko-dev#535]
We've tried to record a feature branch of the XState Visualizer to check something out but unfortunately, the recording just doesn't boot up:
https://app.replay.io/recording/7c5e6240-8132-406c-8c69-0a386fad583b

There might be something off there with multiple, nested iframes, but that's just a guess of what might be happening here.

**Comment by jasonLaster** [comment]
@Andarist just skimmed the logs and came up empty. We'll look into it this week as a case study in how to summarize sessions

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-76](https://linear.app/replay/issue/RUN-76/replay-recording-cant-load)
