### ISSUE TITLE
touch simulation causes replay to miss events

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#536]
![image](https://user-images.githubusercontent.com/254562/134540905-2cb14445-1b6d-4d7d-9522-ab61cdfd6d8a.png)

the replay browser doesn't seem to pass through click events reliably, even though the same site I'm testing works fine in Firefox with this option turned on.

**Comment by ryanjduffy** [comment]
Recording from https://patrickhlauke.github.io/touch/tests/event-listener.html

https://app.replay.io/recording/5f91d7ec-2d46-4c0a-b5b0-2e7623f667db?point=8437482395119655216213295462613238&time=3967&hasFrames=false

Anecdotally, clicking with touch emulation on seems spotty. When recording, no touch events are captured.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-77](https://linear.app/replay/issue/RUN-77/touch-simulation-causes-replay-to-miss-events)
