### ISSUE TITLE
Add support for browser emulations

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#539]
Browser devtools offer a bunch of useful feature for emulating mobile dev which would nice to support

* Responsive Mode https://github.com/RecordReplay/gecko-dev/issues/282
* touch simulation https://github.com/RecordReplay/gecko-dev/issues/536
* 3G and latency

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-78](https://linear.app/replay/issue/RUN-78/add-support-for-browser-emulations)
