### ISSUE TITLE
Windows: enable use of DirectWrite

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#541]
https://github.com/RecordReplay/gecko-dev/commit/86ce2b6b251a7f29f1f30a28e790cfbc1113a1b2 disables use of IDWriteFactory for rendering fonts in gecko, to avoid having to deal with the interfaces used to render fonts via DirectWrite.  It would be good to fix this, as the fallback font rendering strategy which gecko uses draws pretty ugly text in comparison, at least on simple unstyled pages.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-79](https://linear.app/replay/issue/RUN-79/windows-enable-use-of-directwrite)
