### ISSUE TITLE
Banner at top of browser that warns if the recorded site has incompatible technologies gives a link that's unclickable and uncopy-pastable.

### ISSUE THREAD

**Issue by gideonred** [replayio/gecko-dev#544]
When trying to record a site that uses WebGL or Mediaplayback I see a banner as in this screenshot:
![Screen Shot 2021-09-30 at 9 19 06 AM](https://user-images.githubusercontent.com/28845582/135462888-9ddebc10-ed9a-49f4-9eb2-ef518440efc0.png)

This is useful in knowing that there's something I can't record, but I can't click on the link given, and I can't copy and paste it.

I expect to be able to either click on the link or copy and paste it. Retyping it is a lot of friction.

Shout out to Alejandro for spotting this during his interview.

**Comment by ryanjduffy** [comment]
I have some visual cleanup of these warning in my queue already so I’ll be sure to address this.
