### ISSUE TITLE
`alert`, `confirm` and friends don't show up in video

### ISSUE THREAD

**Issue by jazzdan** [replayio/gecko-dev#553]
If a page calls `window.alert`, `confirm`, etc that dialog box doesn't render in the video https://app.replay.io/recording/f40f5993-280b-4d91-a755-0e495b1cebf9

**Comment by loganfsmyth** [comment]
I think the prompt is normally rendered in the parent process, so we may need to record that a prompt opened/closed then render an analogous thing ourselves when replaying.

**Comment by jasonLaster** [comment]
kinda like the mouse 🐭

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-240](https://linear.app/replay/issue/RUN-240/alert-confirm-and-friends-dont-show-up-in-video)
