### ISSUE TITLE
Windows build of Replay browser is rendering at lower resolution

### ISSUE THREAD

**Issue by gideonred** [replayio/gecko-dev#555]
I compared the latest Firefox with the latest build of Replay on Windows. Below is an excerpt of having them side by side on the same screen, left is Firefox, right is Replay:
![WindowsCompare](https://user-images.githubusercontent.com/28845582/137402789-a4e126d0-d6da-4fe5-a9f4-0fbc0abf5c17.png)

For interest here's the entire screenshot:
![Screenshot 2021-10-14 133025](https://user-images.githubusercontent.com/28845582/137402823-95807adf-04c4-4cd5-babd-22efa048e1d3.png)

I'd expect Replay to be rendering at same resolution as Firefox.

**Comment by bhackett1024** [comment]
Some notes from Jason at Glide in their slack are below.  It looks like the problem is we're not setting the high DPI mode for the resulting executable for some reason.

```
11:40 if I right click the .exe -> Compatability -> Change high DPI settings -> and set this [Override high DPI scaling behavior]
11:40 it works right
11:41 I think you're just missing some metadata somewhere telling windows you support hidpi
11:41 does screw up your titlebar however
11:41 but I get hidpi
```

**Comment by bhackett1024** [comment]
Looking through https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process a process can create high DPI windows either in its manifest or via API calls.  I don't see any of the relevant API calls in gecko, and there is a manifest setting that should allow high DPI mode here:

https://github.com/RecordReplay/gecko-dev/blob/9cfb2558294dce5c2feca80dd92667e46cf7dc2f/toolkit/mozapps/defaultagent/default-browser-agent.exe.manifest#L27

It seems most likely that there's something going wrong with this manifest somehow.

**Comment by bhackett1024** [comment]
So, windows manifests are embedded as part of the executable file itself.  It looks like the manifest isn't present in replay.exe:

```
C:\Program Files\replay>mt -inputresource:replay.exe -out:replay.manifest
Microsoft (R) Manifest Tool
Copyright (c) Microsoft Corporation.
All rights reserved.

mt : general error c101008c: Failed to read the manifest from the resource of file "replay.exe". The specified resource type cannot be found in the image file.
```

It is present in a firefox distribution, though there aren't any of the DPI awareness settings reflected for some reason (note that upstream firefox has the same default-browser-agent.exe.manifest, which hasn't been changed in 1.5 years).

```
C:\Program Files\Mozilla Firefox>mt -inputresource:firefox.exe -out:firefox.manifest
Microsoft (R) Manifest Tool
Copyright (c) Microsoft Corporation.
All rights reserved.
```

firefox.manifeset:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
<assemblyIdentity version="1.0.0.0" processorArchitecture="*" name="Firefox" type="win32"></assemblyIdentity>
<description>Firefox</description>
<dependency>
        <dependentAssembly>
                <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" version="6.0.0.0" processorArchitecture="*" publicKeyToken="6595b64144ccf1df" language="*"></assemblyIdentity>
        </dependentAssembly>
</dependency>
<dependency>
        <dependentAssembly>
                <assemblyIdentity type="win32" name="mozglue" version="1.0.0.0" language="*"></assemblyIdentity>
        </dependentAssembly>
</dependency>
<ms_asmv3:trustInfo xmlns:ms_asmv3="urn:schemas-microsoft-com:asm.v3">
  <ms_asmv3:security>
    <ms_asmv3:requestedPrivileges>
      <ms_asmv3:requestedExecutionLevel level="asInvoker" uiAccess="false"></ms_asmv3:requestedExecutionLevel>
    </ms_asmv3:requestedPrivileges>
  </ms_asmv3:security>
</ms_asmv3:trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"></supportedOS>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"></supportedOS>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"></supportedOS>
    </application>
  </compatibility>
</assembly>
```

I'm inclined to see if calling SetProcessDpiAwarenessContext at startup as described in the link above fixes this.  This is more of a workaround than a proper fix, but I'm not sure yet what other value the manifest provides, and figuring out what's going on with the build process here doesn't look simple.

**Comment by bhackett1024** [comment]
The above patch fixes things for me in my windows VM.  Note that SetProcessDpiAwarenessContext is only available in windows 10 or later, so this will only update DPI awareness in those cases.  We dynamically load the procedure so things should still work (just without high DPI) in older versions of windows.
