### ISSUE TITLE
Connection is not authenticated

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#558]
I think that the browser has an old access token so it thinks i'm logged in, but app.replay.io has a different session...

<img width="878" alt="Screen Shot 2021-10-15 at 4 51 06 PM" src="https://user-images.githubusercontent.com/254562/137565234-45c14253-fe0c-4260-a8e8-7de9420ac9e3.png">

https://www.loom.com/share/8b9cd3ff07e449638ae350b2e44d131c

**Comment by loganfsmyth** [comment]
From everything I've seen around this so far when trying to figure it out myself, something is causing us to use an old access token even though it is expired, so the button says Rec even though it has a bad token and should have been updated to say SignIn.
