### ISSUE TITLE
Support Apple Silicon for Gecko Dev

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#559]
The Replay browser is currently a universal app and does not have an Apple Silicon version. This by itself is likely a significant performance issue regardless of whether users are recording or not.

Fun fact, this was actually the first piece of feedback that Guillermo, the CEO of Vercel shared with me.

**Comment by jasonLaster** [comment]
From @bhackett1024 

> recording on ARM would require a large amount of work, it's a completely different architecture from x64.  not worth it IMO unless we have concrete evidence it's causing a big slowdown, and even then probably not worth it until we want to start recording on android/chromium

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-242](https://linear.app/replay/issue/RUN-242/support-apple-silicon-for-gecko-dev)
