### ISSUE TITLE
Windows: Temp directory fills up with record/replay DLLs

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#562]
When a recording content process starts, it creates a temporary file with the record/replay DLL's contents for loading (unless the DLL path was specified via the environment).  We try to delete the file after it has been loaded, which I think works fine on mac/linux but the files stick around on windows, presumably because NTFS doesn't allow deleting a file that is in use.  Unless the temp directory is emptied, it will fill up with copies of the temp DLL.  It would be good to find a way to keep this from happening, either by deleting the temp file after the recording process finishes or by allowing reuse of the temporary driver files.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-243](https://linear.app/replay/issue/RUN-243/windows-temp-directory-fills-up-with-recordreplay-dlls)
