### ISSUE TITLE
Logged out constantly

### ISSUE THREAD

**Issue by Andarist** [replayio/gecko-dev#566]
I'm being logged out from my profile in the Replay browser on a regular basis and I'm currently using it quite often (at least once a day). If that could be avoided it would make for a smoother user experience.

**Comment by jasonLaster** [comment]
I wonder if @ryanjduffy fix will fix this too. either way, probably belongs here...

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-85](https://linear.app/replay/issue/RUN-85/logged-out-constantly)
