### ISSUE TITLE
Show the correct cursor

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#568]
I believe we only store the x/y position of the cursor. It would be nice to also have the type so that we can show the correct pointer in the video

Here's an example mouse event.
```​
clientX: 1286​​​​
clientY: 768
kind: "mousemove"
point: "973555661042562373515314437554219"
time: 2013
```

We should also have cursor which could have keywords like pointer, grab, text, resize...

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-86](https://linear.app/replay/issue/RUN-86/show-the-correct-cursor)
