### ISSUE TITLE
Run in AWS Lambda

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#571]
The https://github.com/alixaxel/chrome-aws-lambda documents what is required to run chromium in AWS Lambda. It should be similar to do the same for gecko-dev

Their repo is pretty good with a lot of documentation and limits from the lambda side:
* Lambda is limited to one CPU thread.
* Lambda is limited to 3GB of RAM.
* Lambda is not provisioned with any fonts.

For example in Lambda you can't open an external browser context, it's just doesn't work
it must run with the --single-process flag
Having this inside of Lambda will really change the bot automation world

https://github.com/alixaxel/chrome-aws-lambda/issues/175

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-87](https://linear.app/replay/issue/RUN-87/run-in-aws-lambda)

**Comment by gideonred** [comment]
Reopening as this has public interest.

**Comment by Domiii** [comment]
We have closed this internally as `wont-fix` for now. If anyone is seriously affected by this, please feel free to reach out.
