### ISSUE TITLE
Example recordings not saved in e2e tests

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#573]
When an e2e test from our devtools repo is run, it creates an example recording and save the recordingId in `example-recordings.json`, so that it won't have to create a new example recording every time. For this to work, the browser prints `CreateRecording <recordingId> <url>` on the command line when creating the recording (see [here](https://github.com/RecordReplay/gecko-dev/blob/d20d948b5293f927b62b08e7f0c85652278db1c2/toolkit/recordreplay/ProcessRecordReplay.cpp#L875)). However, this line is currently missing the url and as a result, the test runner won't save the recordingId in `example-recordings.json`.

**Comment by jcmorrow** [comment]
Took me a while to find this 😆 , here's some context from an issue a few weeks ago: https://github.com/RecordReplay/devtools/issues/3963

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-88](https://linear.app/replay/issue/RUN-88/example-recordings-not-saved-in-e2e-tests)
