### ISSUE TITLE
Windows theme covers up title bar buttons

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#585]
With the fix for https://github.com/RecordReplay/gecko-dev/issues/555 in place, we have a rendering problem now on high DPI displays where the title bar buttons are partially covered up (they can still be clicked though).

<img width="162" alt="Screen Shot 2021-11-09 at 7 22 24 AM" src="https://user-images.githubusercontent.com/1062578/140942676-3ab974c3-4801-456c-8fca-9ca7b62c1f80.png">

It looks to me like there is a mask of some sort that isn't being scaled properly.

**Comment by bhackett1024** [comment]
@ryanjduffy hi, I think this is related to https://github.com/RecordReplay/gecko-dev/pull/370 which added the alpenglow theme.

It looks like this may be a bug in firefox itself, I found a support thread at https://support.mozilla.org/en-US/questions/1087270 about themes on windows 10 where the images are cut off in about the same way as here.

**Comment by ryanjduffy** [comment]
:+1: I'll check it out

**Comment by ryanjduffy** [comment]
We reverted the fix so this needs to be addressed again either by conditionally applying the pref or, ideally, sorting out why the theme does what it does.

**Comment by jasonLaster** [comment]
Adding this screencapture too
https://app.birdeatsbug.com/sessions/i3GgdezY7tZy-5g96sJ2C

**Comment by loganfsmyth** [comment]
<img width="964" alt="Screenshot 2022-01-19 161759" src="https://user-images.githubusercontent.com/132260/150239596-b05f2080-17d2-4f03-91ed-3caa4919b78e.png">

**Comment by ryanjduffy** [comment]
Didn't seem to fix it on HDPI screens so reopening for more investigation.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-250](https://linear.app/replay/issue/RUN-250/windows-theme-covers-up-title-bar-buttons)
