### ISSUE TITLE
Hitting backspace browses back in history.

### ISSUE THREAD

**Issue by gideonred** [replayio/gecko-dev#627]
Hitting backspace while just browsing using the Replay browser makes you go back in history. Firefox does not do this.

Replay: https://app.replay.io/recording/462e26af-1a90-41fc-b454-64acf49567cc?point=20444668882482711772081239162357614&time=7861&hasFrames=false

**Comment by jasonLaster** [comment]
Andarist originally filed this

**Comment by jasonLaster** [comment]
Andarist originally filed this

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-253](https://linear.app/replay/issue/RUN-253/hitting-backspace-browses-back-in-history)
