### ISSUE TITLE
getAllBoundingClientRects: handle inline elements correctly

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#628]
Multiline inline elements create more than one rectangle in the page. Currently we ignore this and use `element.getBoundingClientRect()` which gives us a rectangle that contains all these rectangles, but we should start using `element.getClientRects()` instead.

**Comment by jasonLaster** [comment]
We might want to consider these cases too

> But also for block stuff when split between 2+ columns. Same for paged media. Same for Regions of we had Regions (but we don't). I think that's it.

**Comment by Andarist** [comment]
@jasonLaster block stuff case - when this can happen? Paged media and regions - what? What do you mean by those two? I can imagine some stuff for paged media when it comes to printing and stuff but i have no idea what’s hidden behind regions stuff

**Comment by jasonLaster** [comment]
@Andarist that came from here: https://twitter.com/fvsch/status/1470827502964723712
