### ISSUE TITLE
Replay showing Firefox VPN offer

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#631]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/9154902/145732364-687282c4-d4a3-45ad-91ae-cbd1f42f2363.png">

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-254](https://linear.app/replay/issue/RUN-254/replay-showing-firefox-vpn-offer)
