### ISSUE TITLE
Repaint graphics are broken in MaterialIcon replay

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#634]
The graphics are garbled for this replay:
https://app.replay.io/recording/310026b0-6ddb-4e18-b559-ef616a43cc08

<img width="438" alt="Screen Shot 2021-12-14 at 7 35 18 AM" src="https://user-images.githubusercontent.com/254562/146029313-abf1f66d-238e-4c62-bfca-32627fc62773.png">

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-255](https://linear.app/replay/issue/RUN-255/repaint-graphics-are-broken-in-materialicon-replay)
