### ISSUE TITLE
Improve vscode.dev TTI / TFP

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#635]
STR:
1. go to vscode.dev
2. press record

Notice how it takes awhile for the vscode to load.

replay: https://app.replay.io/recording/3006a6df-4908-4c1a-950f-a546451e8808

**Comment by jasonLaster** [comment]
https://www.loom.com/share/627b06d00ddb4506963f1e7e525e8a2d

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-256](https://linear.app/replay/issue/RUN-256/improve-vscodedev-tti-tfp)
