### ISSUE TITLE
Wrong client rects after executing CSS.getAppliedRules command

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#644]
In recordings of app.replay.io made on MacOS (I couldn't reproduce this with a Linux recording), the client rects we get for the buttons in the toolbar on the left are wrong if they are requested after a `CSS.getAppliedRules` command was executed for the same pause.
This replay shows the problem: https://app.replay.io/recording/6a45ccc7-2fed-4b0d-9b44-7870f769de98
It can also be reproduced with this:

```js
const { sessionId } = await client.sendCommand("Recording.createSession", {
  recordingId: "ca5fd6c0-8d53-43ba-844c-52a378eecf4a"
});
const { pauseId } = await client.sendCommand("Session.createPause", {
  point: "66201784950224524284994824234340831"
}, sessionId);

let widthResult = await client.sendCommand("Pause.evaluateInGlobal", {
  expression: "document.querySelector('.forum').getBoundingClientRect().width"
}, sessionId, pauseId);
console.log(widthResult.result.returned?.value);

const { document } = await client.sendCommand("DOM.getDocument", {}, sessionId, pauseId);
const { result: body } = await client.sendCommand("DOM.querySelector", {
  node: document, selector: "body"
}, sessionId, pauseId);
await client.sendCommand("CSS.getAppliedRules", { node: body }, sessionId, pauseId);

widthResult = await client.sendCommand("Pause.evaluateInGlobal", {
  expression: "document.querySelector('.forum').getBoundingClientRect().width"
}, sessionId, pauseId);
console.log(widthResult.result.returned?.value);
```
This code will log first `24` and then `0` as the button width.
While this example uses evaluations to get the button's bounding client rect, Ive seen the same issue with client rects from the `DOM.getBoundingClientRect` and `DOM.getAllBoundingClientRects` commands.
Note that the buttons for which we get a width of 0 use the Material Icons font, so maybe this is related to #634.

**Comment by jasonLaster** [comment]
I can reproduce this on my Mac OS by recording our DevTools and highlighting a material icon especially the left toolbar

https://www.loom.com/share/a339bc7136a7444bbc170e742af66542

* [replay 1](https://app.replay.io/recording/7bd121c4-c47c-42d2-8329-1fc135c8d78b#
)
* [replay 2](https://app.replay.io/recording/f9702724-fde7-4ff6-b47d-d693d1f3ab0a?point=20769187437857387826915689053029497&time=8450&hasFrames=false)

**Comment by hbenl** [comment]
I couldn't reproduce this in new recordings anymore, perhaps it was fixed by the ESR rebase.
