### ISSUE TITLE
Ensure that user credentials are passed along when loading sourcemap assets

### ISSUE THREAD

**Issue by loganfsmyth** [replayio/gecko-dev#646]
At the moment we're seeing some cases of sourcemap loading getting 401s and from talking with the client it sounds like they have basic-auth on their sourcemap assets, so we'll need to make sure that the basic-auth credentials get passed along properly when requesting sourcemaps.

**Comment by loganfsmyth** [comment]
It's possible that we just need to add `credentials: "include",` to the `fetch` call, but it really depends on how `fetch` behaves when running in the parent process.

**Comment by loganfsmyth** [comment]
https://gist.github.com/loganfsmyth/0c04ab7dbb70349cdc0762aca6e483cb

**Comment by jasonLaster** [comment]
re-opening because this did not fix the issue

**Comment by ryanjduffy** [comment]
Hopefully fixed by #667
