### ISSUE TITLE
ReferenceError: initAuth is not defined

### ISSUE THREAD

**Issue by bhackett1024** [replayio/gecko-dev#656]
This error is showing up a lot in our CI runs.  The tests seem to be passing OK (https://raw.githubusercontent.com/RecordReplay/build-test-dashboard/master/c3d5ac0b-45b1-4b3f-b0f0-53680bc243c1?token=GHSAT0AAAAAABIM7QFFMANIDP53SUIB6W72YPFQXTA) but sometimes we fail to create recordings and I don't know if that's related.  cc @ryanjduffy 

```
JavaScript error: resource:///modules/DevToolsStartup.jsm, line 429: ReferenceError: initAuth is not defined
```

**Comment by ryanjduffy** [comment]
Thanks, @bhackett1024. Looks like some missed cruft from my last change. I'll patch it now.
