### ISSUE TITLE
Some playwright recordings contain an unusable endpoint

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#665]
Many of the example recordings that we now create with playwright for our e2e tests contain an endpoint that is unusable.
devtools usually jumps to the first comment or the first meaningful paint, but when running a test, it jumps to the recording's endpoint and at that point some protocol commands fail, e.g. `DOM.getDocument` returns an error "Document is unavailable", `Pause.evaluateInGlobal` returns `{"result":{"data":{}}}`...

STR:
- make a playwright recording of `doc_stacking.html`
- run devtools locally and comment out https://github.com/RecordReplay/devtools/blob/771fd7fe63eeb54118de7e15d30d31ca355e738c/src/ui/actions/timeline.ts#L108-L113
- view the recording with local devtools

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-260](https://linear.app/replay/issue/RUN-260/some-playwright-recordings-contain-an-unusable-endpoint)
