### ISSUE TITLE
Gecko Help sends you to a Notion page called "Old Replay Docs"

### ISSUE THREAD

**Issue by gideonred** [replayio/gecko-dev#666]
When doing:

Burger Menu -> Help -> Replay Help you are redirected to https://www.notion.so/Old-Replay-Docs-56758667f53a4d51b7c6fc7a641adb02 . Which is titled "Old Replay Docs".

Expected behavior: Get a document not titled "Old".

cc @ceceliacreates , you may have an opinion of what document we should link to.

**Comment by ceceliacreates** [comment]
Unless we have a support landing page, then I would link to docs here: https://docs.replay.io/docs

As an aside -- eventually a support landing page would be nice to direct people to the docs, Discord, GitHub issues, and/or a support email address depending on what they need.

**Comment by jasonLaster** [comment]
good call. It should definetely be https://docs.replay.io/docs
