### ISSUE TITLE
`OPTIONS` Requests never seem to have `request-done` events

### ISSUE THREAD

**Issue by jcmorrow** [replayio/gecko-dev#690]
This at least happens for GraphQL requests on the devtools front-end. E.g. https://app.replay.io/recording/comment-wrong-date--70712306-d9ad-47f9-9bb5-565f73ce56d9. This is easiest to see if you add a print statement around line 146 of `src/ui/components/NetworkMonitor/utils.ts`.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-264](https://linear.app/replay/issue/RUN-264/options-requests-never-seem-to-have-request-done-events)
