### ISSUE TITLE
Stacking: apply pointer-events to all iframe children

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#692]
When an iframe has the CSS property `pointer-events: none`, the iframe's entire content doesn't receive pointer events, but our stacking algorithm currently doesn't apply the iframe's pointer-events property to its children.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-265](https://linear.app/replay/issue/RUN-265/stacking-apply-pointer-events-to-all-iframe-children)
