### ISSUE TITLE
Stacking: iframes never overflow

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#693]
The document inside an iframe never overflows the iframe, even if the iframe's overflow CSS property is set to visible.

**Comment by jasonLaster** [comment]
@hbenl can you add some more context?

**Comment by hbenl** [comment]
@jasonLaster Our stacking algorithm currently lets you select an element in an iframe even if the element is completely invisible because it is positioned outside of the iframe's bounds.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-266](https://linear.app/replay/issue/RUN-266/stacking-iframes-never-overflow)
