### ISSUE TITLE
Update icon should be Replay fuchsia rather than Firefox mint

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#695]
Current experience:
<img width="333" alt="image" src="https://user-images.githubusercontent.com/9154902/151227974-9db38713-77b1-4fdb-9523-3525ea1bae97.png">

Both of those mint green colours should be Replay fuchsia: #F02D5E

**Comment by jasonLaster** [comment]
@jonbell-lot23 it'd be nice to design a more obvious update button. Perhaps similar to our current warning bars which appear between the page and the url bar?

**Comment by jonbell-lot23** [comment]
Good point @jasonLaster -- hey @ryanjduffy do you happen to recall where that ticket went? I can't find it, and I can't find it in Figma because it's been archived.

Note to self: when I find that design again, I need to make it part of the official Figma design system.

**Comment by ryanjduffy** [comment]
@jonbell-lot23 see https://github.com/RecordReplay/gecko-dev/issues/523

**Comment by jonbell-lot23** [comment]
I made a new ticket for the banner idea: https://github.com/RecordReplay/gecko-dev/issues/714

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-268](https://linear.app/replay/issue/RUN-268/update-icon-should-be-replay-fuchsia-rather-than-firefox-mint)
