### ISSUE TITLE
logpoint performance

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#71]
STR:

1. about:webreplay?recording={a826fb3f-414e-5f46-b850-3c050a4c3a75}
2. add a logpoint in `react-instantsearch-dom/dist/es/components/Hits.js:24`  with the expression `"Hits:", hits[0]`

the 20 or so hits take awhile to load and occassionally crash

**Comment by bhackett1024** [comment]
Hmm, when loading the recording I only see the webpack file and not the original sources.  What line in the generated file should the logpoint be added to?
