### ISSUE TITLE
Some playwright recordings don't contain sourcemaps

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#717]
It is possible to create gecko/playwright recordings containing sourcemaps if the recording is uploaded directly (instead of saved to disk and uploaded later), see #435. But I've noticed when creating example recordings for our e2e tests that these recordings are sometimes stuck on "Uploading sourcemaps" and sometimes don't contain sourcemaps at all.
I was able to work around that by adding a 1 second delay before calling `browser.close()`, apparently this is necessary to wait for the browser to load the sourcemaps - it would be nice if it would automatically wait until all sourcemaps are loaded.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-274](https://linear.app/replay/issue/RUN-274/some-playwright-recordings-dont-contain-sourcemaps)
