### ISSUE TITLE
Playwright in direct upload mode creates multiple recordings

### ISSUE THREAD

**Issue by hbenl** [replayio/gecko-dev#719]
In RecordReplay/devtools#5217 I'm trying to record our e2e test examples with playwright uploading the recording data directly (by setting the `RECORD_REPLAY_SERVER` env variable, see #435). The logs of the CI test runs for that PR show that playwright is creating multiple recordings when recording an example. Most of them seem to be unusable.

**Comment by bhackett1024** [comment]
We record all content processes when using playwright, but firefox creates multiple pre-loaded processes which no content is ever loaded into.  These are fine to ignore as long as we can determine the recording which we're actually interested in.  The replay-recordings npm module / CLI tool is good for this as it will show the loaded-url metadata for each recording which has been created.  I think it will automatically ignore the processes which never did anything as well.

**Comment by hbenl** [comment]
OK, so this is expected behaviour. It doesn't create any problems because playwright will only write out the recordingId of the recording that we're interested in (this is in direct upload mode where the recordingId is written to a file).
I was just investigating why some of the example recordings made in this way are unusable and thought this may be related.
