### ISSUE TITLE
Sometimes no 'response' or 'response-done' network events are emitted even though the response has data

### ISSUE THREAD

**Issue by loganfsmyth** [replayio/gecko-dev#725]
See https://github.com/RecordReplay/customer-support/issues/25 for more details.

**Comment by jcmorrow** [comment]
I don't have access to the original Replay in that customer support issue, but it is possible that this was a request that was going to a service worker, which won't emit `http-on-examine-response`.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-275](https://linear.app/replay/issue/RUN-275/sometimes-no-response-or-response-done-network-events-are-emitted-even)
