### ISSUE TITLE
Create an end-to-end test suite

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#73]
- i wonder if we can start writing "unstable" mochitests that use real world examples
- the ideal test would, start firefox with recording, go to the storybook example page (or any other real site), perform some actions, and then save...
- basically go from small tests to something real users are doing

**Comment by jasonLaster** [comment]
https://www.npmjs.com/package/puppeteer-firefox

selenium

**Comment by bhackett1024** [comment]
In the backend we now have an end-to-end test that creates a recording on the todomvc page, saves it, replays it, and interacts with it, all using the same DMG and method for connecting to the cloud which people who downloaded the browser will use.

This will improve soon with more tests on a variety of more complicated real websites, but this is already a huge step forward for our testing infrastructure.
