### ISSUE TITLE
Excalidraw Node Picker

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#742]
The Node Picker misses the UI Controls in Excalidraw

https://www.loom.com/share/585d21537c2040cb82321471fcb6688d

**Comment by hbenl** [comment]
Could you share the recording? In this recording it works perfectly:
https://app.replay.io/recording/excalidraw--d48efc4d-c018-4d75-8f91-ca1f6d4acc6d

**Comment by jasonLaster** [comment]
Weird you're right - even this replay at different points work too
https://app.replay.io/recording/excalidraw--b6ea6f10-c164-444d-81c2-1c26456318e5?point=29855706939069938886503603311215969&time=11982&hasFrames=true

**Comment by jasonLaster** [comment]
How do you want to prioritize this? I could go either way since it is more limited

**Comment by hbenl** [comment]
I'd like to work on it as soon as we can reproduce it. But since that's currently not the case I'll take it out of the Sprint.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-277](https://linear.app/replay/issue/RUN-277/excalidraw-node-picker)
