### ISSUE TITLE
Getting started with gecko-dev

### ISSUE THREAD

**Issue by jcmorrow** [replayio/gecko-dev#745]
I'm just making this issue to document my getting up-and-running experience. If everything goes smoothly there won't be many updates to make, but if I get stuck hopefully this can be a place to gather some additional docs/work to improve the process.

**Comment by gideonred** [comment]
So I like the ticket, but I'm wondering if we should create tickets like this in a private repo when it doesn't have public open source value.

**Comment by jcmorrow** [comment]
Yeah, I was wondering where to put this, and I sort of felt like the value of it being colocated with the code was worth it. If it turns into README updates or additional documentation (or just helps other random people get through a gecko-dev build) that seems fine? IDK, happy to have feedback on this!

**Comment by jcmorrow** [comment]
Summary from Mob Debugging with Dragan, Kannan, Ryan, Jason:

- If you are building on an M1 you will definitely want to follow all of the instructions from a Rosetta terminal,
- If you have partially run `./mach build` and are now stuck, consider blowing away your `mozbuild` directory (`rm -rf ~/.mozbuild`)
- Again, this is an M1 thing, but we saw that `./mach build` tried to install M1 architecture rust, even though it was run from inside of a Rosetta terminal, so if you are getting errors about rust and rust deps, consider using rustup to manually install `x_86` rust, and then installing the needed libraries by hand with `cargo install` (maybe we can put a list of the things you needed to install manually @abstractalgo?)

**Comment by abstractalgo** [comment]
On M1, we had these additional things:

- `rustup default stable-x86_64-apple-darwin`
- `cargo install cbindgen`
- `arch -arm64 brew install nasm`

We ran `./mach bootstrap` from `gecko-dev` and that eventually worked while neither from `mozilla-central` nor `mozilla-unified` (we tried that as well) worked.

**Comment by abstractalgo** [comment]
The prerequisite for everything was going to MacOS's `Applications` > `Utilities` folder, making a copy of `Terminal` app there and renaming it to `Rosetta Terminal`.

**Comment by jcmorrow** [comment]
@gideonred I saw that you added this line about `mozilla-central` (https://github.com/RecordReplay/gecko-dev/commit/c05f9c56f6cd27763021f3f6ff66e0e1aa1878d1). In the setup we were doing today that didn't seem needed, do you remember what problem that solved for you? It would be awesome if we could pinpoint when this is or isn't necessary.

**Comment by gideonred** [comment]
@jcmorrow I added that based on a back and forth between Brian, Logan and Kannan: https://discord.com/channels/779097926135054346/801228428115312671/938567563644915713

If it ended not being needed, let's remove it.

**Comment by jcmorrow** [comment]
Ah, gotchya, yeah that would have helped yesterday, I'll add a note about it in the Troubleshooting section:

```
kannan (he/him) — 02/02/2022
Getting this build error on gecko-dev's mach bootstrap.  Looking into it but wondering if anyone else ran into it: ERROR!!!!!! Could not find artifacts for a toolchain build named macosx64-dump-syms. Local commits, dirty/stale files, and other changes in your checkout may cause this error. Make sure you are on a fresh, current checkout of mozilla-central. Beware that commands like mach bootstrap and mach artifact are unlikely to work on any versions of the code besides recent revisions of mozilla-central.
well maybe a node build will work without that using the prior bootstrap
bhackett — 02/02/2022
@kannan (he/him) you might need to check out a current mozilla-central tip in order to bootstrap successfully, I think @loganfsmyth (he/him) ran into the same issue
loganfsmyth (he/him) — 02/02/2022
Ah yeah that's the same error I got
kannan (he/him) — 02/02/2022
thanks!
kannan (he/him) — 02/02/2022
Like in a fresh repo, run boostrap against that, and then come back to this repo?
loganfsmyth (he/him) — 02/02/2022
Yeah, I cloned MC then did ./mach bootstrap there then went back to gecko-dev and ./mach build worked right
```
