### ISSUE TITLE
Fix Mac download window

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#753]
The Mac download window has a gap of white background in the background image:

![image](https://user-images.githubusercontent.com/9154902/158294943-321bbbee-0000-4d47-9c18-e12a48357bf7.png)

We can also update the background image to fit closer to our brand. Stay tuned for that.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-280](https://linear.app/replay/issue/RUN-280/fix-mac-download-window)
