### ISSUE TITLE
Automatically stay up-to-date with the playwright upstream

### ISSUE THREAD

**Issue by jcmorrow** [replayio/gecko-dev#758]
Right now we can only run on `playwright/test@1.18` because playwright has added some new api usage that our fork does not support. We should be more proactive about pulling in upstream changes as long as we are going to direct people to use `playwright/test` with our playwright fork. An interim solution is to add a peerDependency for a particular version of playwright to our `recordReplay/cli` (for right now we'll do it on playwright-config unless that gets absorbed to `replay-cli` before I get to it): https://github.com/RecordReplay/playwright-config/issues/3

**Comment by jcmorrow** [comment]
For context, it's the jump from FF 96 -> 97 that causes playwright 1.20 to break

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-281](https://linear.app/replay/issue/RUN-281/automatically-stay-up-to-date-with-the-playwright-upstream)
