### ISSUE TITLE
Containerize a stateless build of gecko-dev on macOS

### ISSUE THREAD

**Issue by kannanvijayan** [replayio/gecko-dev#777]
In pursuit of a more modular build/test system for the browser, let's start by implementing a stateless containerized build of gecko-dev on macOS.

Deliverables:

1. Dockerfile that can build a parameter-specified revision/branch from scratch
2. A shell script that invokes said Dockerfile, accepting the revision/branch as a command-line parameter
  - Script can assume that an employee with the correct credentials/environment is invoking it

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-282](https://linear.app/replay/issue/RUN-282/containerize-a-stateless-build-of-gecko-dev-on-macos)
