### ISSUE TITLE
Additional response bodies

### ISSUE THREAD

**Issue by jaril** [replayio/gecko-dev#825]
We should get response bodies for images, html, and other simple data types.

- [x] https://github.com/RecordReplay/gecko-dev/pull/820
- [ ] https://github.com/RecordReplay/gecko-dev/issues/824
- [ ] https://github.com/RecordReplay/gecko-dev/issues/823
- [ ] https://github.com/RecordReplay/gecko-dev/issues/822

(Created from the [Replay Roadmap Airtable](https://airtable.com/appSzSiRS6UdFlXKj/tblpTtDTV98hPX4m0/viwyIRSTFuDV9bzCx?blocks=hide))

**Comment by jaril** [comment]
@jcmorrow still getting around to this this month?

**Comment by jcmorrow** [comment]
Yeah I expect so 👍

**Comment by jaril** [comment]
Added it to next sprint — let me know if that's not the right place for it!

**Comment by jcmorrow** [comment]
Eh, tbh this should probably be "in progress" until I break it up into smaller cards

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-290](https://linear.app/replay/issue/RUN-290/additional-response-bodies)
