### ISSUE TITLE
Can't launch ext auth from linux

### ISSUE THREAD

**Issue by ryanjduffy** [replayio/gecko-dev#832]

**Comment by ryanjduffy** [comment]
Tried this on Ubuntu 20.04 on a linux VM and it launched Firefox successfully when clicking sign in.

**Comment by ryanjduffy** [comment]
cc: @hbenl ^^^

**Comment by hbenl** [comment]
Huh, I just tried again and now it works for me too ¯\\\_(ツ)_/¯
