### ISSUE TITLE
Sanitize `GetConsoleMessageData` within `OnConsoleMessage` handler

### ISSUE THREAD

**Issue by kannanvijayan** [replayio/gecko-dev#855]
See backend comment: https://github.com/RecordReplay/backend/issues/5772#issuecomment-1138934270

`GetConsoleMessageData` can end up calling into browser code in a way that eventually causes reflows and new text calculations.  Figure out if that's an expected thing, and if not, fix the behaviour of `GetConsoleMessageData` to only passively query the page data and not cause reflows to happen.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-294](https://linear.app/replay/issue/RUN-294/sanitize-getconsolemessagedata-within-onconsolemessage-handler)
