### ISSUE TITLE
Sign-in requires restart of Replay Browser

### ISSUE THREAD

**Issue by ceceliacreates** [replayio/gecko-dev#857]
Recorded a Loom video -- Sign in button redirects and I log in, but have to restart the Replay browser for the sign-in to take effect.

https://www.loom.com/share/300e8238db2e431fb513725d59510453

Build macOS-gecko-20220520-08e1183a3e90-c9526a9aeeb2 (64-bit)

**Comment by loganfsmyth** [comment]
cc @ryanjduffy

**Comment by ryanjduffy** [comment]
I just had this happen too. I made the mistake of "fixing" it by logging out of app.replay.io and now it won't repro for me :/

**Comment by ceceliacreates** [comment]
Created a Loom of this error: https://www.loom.com/share/2ac7af6ab0cc4ec79cee90acdba0740a

As @hbenl mentioned in Discord, it does look like the browser is holding on to an expired token.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-295](https://linear.app/replay/issue/RUN-295/sign-in-requires-restart-of-replay-browser)
