### ISSUE TITLE
Our Settings Import feature is broken

### ISSUE THREAD

**Issue by jonbell-lot23** [replayio/gecko-dev#859]
Here's a Loom of it failing: https://www.loom.com/share/c35b867ed4ee4fd29d9a645634b91cf4

Here's what I see in the console: 
<img width="777" alt="image" src="https://user-images.githubusercontent.com/9154902/171286404-22519233-ace1-45c7-879a-e0455517819f.png">

**Comment by ryanjduffy** [comment]
Fixed by https://github.com/RecordReplay/devtools/pull/7005
