### ISSUE TITLE
[pinterest] Portions of the screen are painted black

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#861]
When I record the homepage of pinterest.com and a product page i see black graphics on the screen. 

* https://app.replay.io/recording/2824-pinterest--80166673-ec7d-47d9-a87f-7f392e3763a3?point=4543259751219680498791002421593314&time=1593&hasFrames=false#

* https://app.replay.io/recording/2824-pinterest--e3ae14cd-c518-4fe8-8780-aa2d2be1fadb?point=18822076120432477870284359484837560&time=7393&hasFrames=false#

**Comment by jasonLaster** [comment]
https://www.loom.com/share/d5188ef8bfae468e93e34bfec01635bf

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-296](https://linear.app/replay/issue/RUN-296/[pinterest]-portions-of-the-screen-are-painted-black)
