### ISSUE TITLE
Playwright tests should include a last screen

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#866]
We are currently writing the sourcemaps and recording to disk, but we're not writing the last screen to disk or metadata so it is lost

**Comment by bhackett1024** [comment]
Can we just extract the last screen from the recording itself via the protocol?

**Comment by ryanjduffy** [comment]
That's where my head went as well

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-297](https://linear.app/replay/issue/RUN-297/playwright-tests-should-include-a-last-screen)
