### ISSUE TITLE
Prefer login over API key when recording manually and not via CLI

### ISSUE THREAD

**Issue by ceceliacreates** [replayio/gecko-dev#869]
Generated from https://github.com/replayio/customer-support/issues/123

Currently, if an API key is set via environment variable RECORD_REPLAY_API_KEY, recording in the Replay Browser will use this API key instead of the logged in user information.

Suggested fix:

change hasOriginalApiKey() and getOriginalApiKey() so that they only return the environment API key if RECORD_ALL_CONTENT is set.

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-299](https://linear.app/replay/issue/RUN-299/prefer-login-over-api-key-when-recording-manually-and-not-via-cli)
