### ISSUE TITLE
Cannot record react-devtools shell

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#872]
This replay does not load the app below
https://app.replay.io/recording/react-devtools--fcc2fa4b-0483-4bb8-9eb8-4d71baa1ba32

STR: follow the steps to run react-devtools-shell and react-devtools-inline locally

NOTE:

It should look like this
<img width="1512" alt="Screen Shot 2022-06-07 at 5 44 37 PM" src="https://user-images.githubusercontent.com/254562/172679179-c21278b7-fdc7-4aec-8de1-fd3bb4c82eb8.png">

but instead looks like this
<img width="1512" alt="Screen Shot 2022-06-07 at 5 44 37 PM" src="https://user-images.githubusercontent.com/254562/172679229-f8e715d0-34ad-4ef6-a3ff-0ac441793940.png">

**Comment by bvaughn** [comment]
Those screenshots look _exactly_ the same to me. What am I missing?

**Comment by gideonred** [comment]
This ticket has been moved to [RUN-300](https://linear.app/replay/issue/RUN-300/cannot-record-react-devtools-shell)
