### ISSUE TITLE
Adding additional console.logs decreased stability

### ISSUE THREAD

**Issue by jasonLaster** [replayio/gecko-dev#97]
From Jeff Lasslett:

I just thought I'd let you know that I added more console.log() statements to my software yesterday.
This appeared to lead to increased instability.  Web Replay went back to taking a minutes to load and then crashing without interaction.

I sent through the resulting crash reports.

**Comment by bhackett1024** [comment]
After reviewing the server log from this session, this is what happened:

* We queue up a bunch of requests on different processes to get the pause data for different console.log() calls.

* These pause data requests finish at about the same time and send out a lot of data back to the user.

* The pause data takes a while to download, and while they are being downloaded other messages aren't getting through.

* A couple processes are marked as hanged, even though they finished their operations successfully --- their responses to the user didn't get through while the pause data was downloading.

* A bug in the crash recovery code kept us from respawning the hanged processes successfully.  We kept spawning new processes, giving them some broken instructions, after which they crashed and we spawned another new one.

* Eventually we give up and crash the tab.

I'll fix the crash recovery bug right now.  The lack of responsiveness during large data transfers is a more general problem covered in https://github.com/WebReplay/webreplay/issues/84.  When that is fixed (should be done in a day or two), I think this page will feel a lot more stable / responsive.

**Comment by bhackett1024** [comment]
The large data transfers which led to this crash should be much much smaller now (see https://github.com/WebReplay/webreplay/issues/84), so this should be stable even with a bunch of console logs.  Feel free to reopen if there are still problems, though.
